import type { PlacementScenario, PolicyPlaceholder } from './types.ts';

export const DEFAULT_SCENARIOS: PlacementScenario[] = [
  {
    id: '1v1_equal_ratings',
    title: '1v1 equal ratings',
    description: 'Two established 1500-rated players; A beats B.',
    mode: '1v1',
    playerCount: 2,
    players: [
      { id: 'A', rating: 1500, matchesPlayed: 20 },
      { id: 'B', rating: 1500, matchesPlayed: 20 },
    ],
    placements: [['A'], ['B']],
    tags: ['1v1', 'baseline'],
  },
  {
    id: '1v1_upset',
    title: '1v1 upset',
    description: 'Lower-rated B beats higher-rated A.',
    mode: '1v1',
    playerCount: 2,
    players: [
      { id: 'A', rating: 1700, matchesPlayed: 20 },
      { id: 'B', rating: 1500, matchesPlayed: 20 },
    ],
    placements: [['B'], ['A']],
    tags: ['1v1', 'upset'],
  },
  {
    id: '1v1_provisional_win',
    title: '1v1 provisional win',
    description: 'Provisional A beats established B; acceleration applies only to A.',
    mode: '1v1',
    playerCount: 2,
    players: [
      { id: 'A', rating: 1500, matchesPlayed: 2 },
      { id: 'B', rating: 1500, matchesPlayed: 20 },
    ],
    placements: [['A'], ['B']],
    tags: ['1v1', 'provisional'],
  },
  {
    id: '1v1_draw_equal_guesses',
    title: '1v1 draw equal guesses',
    description: 'Two established equal-rating standard/classic players tie on solve quality.',
    mode: '1v1',
    playerCount: 2,
    players: [
      { id: 'A', rating: 1500, matchesPlayed: 20 },
      { id: 'B', rating: 1500, matchesPlayed: 20 },
    ],
    placements: [['A', 'B']],
    tags: ['1v1', 'draw'],
  },
  {
    id: '1v1_inactive_return_win',
    title: '1v1 inactive return win',
    description: 'A long-inactive established player beats an active equal-rated opponent; Glicko-style RD inflation makes A move faster.',
    mode: '1v1',
    playerCount: 2,
    players: [
      { id: 'A', rating: 1500, matchesPlayed: 20, ratingDeviation: 80, inactiveDays: 120 },
      { id: 'B', rating: 1500, matchesPlayed: 20, ratingDeviation: 80 },
    ],
    placements: [['A'], ['B']],
    tags: ['1v1', 'inactive'],
  },
  {
    id: '3p_mixed_skill',
    title: '3-player mixed skill placements',
    description: 'A 1600 player wins, 1500 middle, 1400 last.',
    mode: 'multiplayer',
    playerCount: 3,
    players: [
      { id: 'A', rating: 1600, matchesPlayed: 20 },
      { id: 'B', rating: 1500, matchesPlayed: 20 },
      { id: 'C', rating: 1400, matchesPlayed: 20 },
    ],
    placements: [['A'], ['B'], ['C']],
    tags: ['multiplayer', '3p'],
  },
  {
    id: '4p_equal_placements',
    title: '4-player equal ratings',
    description: 'Four established 1500-rated players finish A > B > C > D.',
    mode: 'multiplayer',
    playerCount: 4,
    players: ['A', 'B', 'C', 'D'].map((id) => ({ id, rating: 1500, matchesPlayed: 20 })),
    placements: [['A'], ['B'], ['C'], ['D']],
    tags: ['multiplayer', '4p', 'baseline'],
  },
  {
    id: '4p_upset',
    title: '4-player upset',
    description: 'B beats stronger A, with C and D below.',
    mode: 'multiplayer',
    playerCount: 4,
    players: [
      { id: 'A', rating: 1700, matchesPlayed: 20 },
      { id: 'B', rating: 1500, matchesPlayed: 20 },
      { id: 'C', rating: 1500, matchesPlayed: 20 },
      { id: 'D', rating: 1300, matchesPlayed: 20 },
    ],
    placements: [['B'], ['A'], ['C'], ['D']],
    tags: ['multiplayer', '4p', 'upset'],
  },
  {
    id: '4p_middle_tie',
    title: '4-player middle tie',
    description: 'Equal ratings with B and C tied in the middle.',
    mode: 'multiplayer',
    playerCount: 4,
    players: ['A', 'B', 'C', 'D'].map((id) => ({ id, rating: 1500, matchesPlayed: 20 })),
    placements: [['A'], ['B', 'C'], ['D']],
    tags: ['multiplayer', '4p', 'tie'],
  },
  {
    id: 'abandon_last_after_meaningful_play_placeholder',
    title: 'Abandon placeholder — last after meaningful play',
    description: 'Policy placeholder: if meaningful play is later approved, abandoning D is treated as last.',
    mode: 'policy_placeholder',
    playerCount: 4,
    players: ['A', 'B', 'C', 'D'].map((id) => ({ id, rating: 1500, matchesPlayed: 20 })),
    placements: [['A'], ['B'], ['C'], ['D']],
    tags: ['abandon', 'policy-placeholder'],
    policyNote: 'Meaningful-play threshold is not locked; this scenario models only the candidate last-place treatment.',
  },
];

export const POLICY_PLACEHOLDERS: PolicyPlaceholder[] = [
  {
    id: 'last_place_after_meaningful_play',
    title: 'Last-place after meaningful play',
    status: 'not_locked',
    simulationTreatment: 'Model abandoning player as last only after product-approved meaningful-play threshold.',
    openDecision: 'Exact meaningful-play threshold is still required.',
  },
  {
    id: 'fixed_penalty_no_opponent_windfall',
    title: 'Fixed penalty plus no opponent windfall',
    status: 'not_locked',
    simulationTreatment: 'Reserved for future simulation; not applied to current candidate comparison.',
    openDecision: 'Need policy decision on whether opponents should receive full, partial, or no rating gains.',
  },
  {
    id: 'void_early_no_meaningful_play',
    title: 'Void early/no meaningful play',
    status: 'not_locked',
    simulationTreatment: 'No rating deltas should be emitted for early/server-integrity voids.',
    openDecision: 'Need server-side definition of early abandon, server fault, and admin void states.',
  },
];
