import assert from 'node:assert/strict';
import { Readable } from 'node:stream';
import { test } from 'node:test';

import { mkdtemp, chmod, symlink, rm, readFile, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { MIGRATIONS, PREFLIGHT_SQL, ROLLBACK_ORDER, canonicalJson, normalizeJsonContentType, parsePreflightArgs, receiptFor, runActivationPreflight, validateInventory, validateRollbackOrder, verifyPreflightReceipt } from './auth-activation-preflight-core.mjs';
import { collectInventory as collectProviderInventory, createReceipt as createProviderReceipt } from './provider-provenance-core.mjs';
import { collectionConstraints, expectedIdentities as fixtureExpectedIdentities, validProviderSnapshot } from './provider-provenance-fixture.mjs';
import { accountFingerprint, parseSmokeArgs, readProtectedStdin, runAuthActivationSmoke, SMOKE_RECONCILIATION_SQL, validateApproval } from './auth-activation-smoke-core.mjs';
import { consumeApprovalDurably } from './auth-activation-consumption.mjs';
import { APPLICATION_MANIFEST_DIGEST, APPLICATION_MODEL_TABLES } from './complete-database-fingerprint.mjs';

const NOW=Date.parse('2026-07-29T12:00:00.000Z'),fp='b'.repeat(16),hostFp='e'.repeat(64);
const nativeEvidence=validProviderSnapshot({collectedAt:'2026-07-29T12:00:00.000Z',nonce:'smoke-run-255'});
const expectedIdentities=fixtureExpectedIdentities(nativeEvidence);
const providerReceiptKey=Buffer.from('ticket-266-offline-fixture-receipt-key-material');
const providerInventory=collectProviderInventory(nativeEvidence,collectionConstraints(nativeEvidence));
const providerReceipt=createProviderReceipt(providerInventory,nativeEvidence,providerReceiptKey,'ticket266-key',collectionConstraints(nativeEvidence));
const production=providerInventory.environments.production,preview=providerInventory.environments.preview;
function inventory(overrides={}) { return {schemaVersion:3,activationPhase:'canary',runId:providerInventory.nonce,sourceSha:production.railway.artifact.sourceGitSha,artifactSha:production.railway.artifact.artifactDigest.slice(7),provider:{projectId:production.railway.identity.projectId,environmentId:production.railway.identity.environmentId,apiServiceId:production.railway.identity.serviceId,webServiceId:production.vercel.identity.projectId,databaseId:production.postgresql.observations[0].databaseId,previewEnvironmentId:preview.railway.identity.environmentId,previewDatabaseId:preview.postgresql.observations[0].databaseId},deployments:{apiDeploymentId:production.railway.identity.deploymentId,apiRevision:production.railway.artifact.sourceGitSha,webDeploymentId:production.vercel.identity.deploymentId,webRevision:production.vercel.artifact.sourceGitSha},origins:{api:'https://api.example.test',web:'https://www.example.test',previewApi:'https://preview-api.example.test',previewWeb:'https://preview.example.test'},replicas:{expected:1,observed:1,observedReplicaId:'replica-api-1'},config:{authMode:'session_required',durableAuth:true,registrationMode:'canary',appEnvironment:'production',nodeEnvironment:'production',secureCookie:true,hostOnlyCookie:true,proxyHops:1,requiredKeysPresent:['AUTH_RATE_LIMIT_KEY','DATABASE_URL'],keyFingerprint:fp,configFingerprint:'c'.repeat(16)},migrations:MIGRATIONS.map((id)=>({id,status:'applied'})),database:{identityFingerprint:'d'.repeat(64),databaseHostFingerprint:hostFp,schemaStatus:'ok',remediationConflictCount:0},source:{kind:'provider-read-only',observedAt:providerInventory.collectedAt},expiresAt:'2026-07-29T12:10:00.000Z',...overrides}; }
function authenticatedInputs(operationalInventory=inventory(),overrides={}) { return {operationalInventory,providerEvidenceLane:'fixture-v2-test-only',providerInventory,providerReceipt,nativeEvidence,expectedNonce:nativeEvidence.nonce,expectedIdentities,providerReceiptKey,...overrides}; }
const dep=(status='ok')=>({status,checkedAt:'2026-07-29T11:59:30.000Z',message:'safe'});
function ready(inv,preview=false){const dormant=inv.activationPhase==='dormant';return{status:'ok',service:'wordle-royale-api',environment:'production',revision:preview?'f'.repeat(40):inv.deployments.apiRevision,checkedAt:'2026-07-29T11:59:30.000Z',dependencies:{database:dep(),applicationSchema:dep(),durableAuth:preview||dormant?{...dep('not_checked_stub'),registrationMode:'closed'}:{...dep(),registrationMode:inv.config.registrationMode,keyFingerprint:inv.config.keyFingerprint,configFingerprint:inv.config.configFingerprint,expectedReplicaCount:1},standardDictionary:dep(),speedRuntime:dep(),speedLifecycleActivation:dep(),redis:dep()}};}
const common=(id,label,players,enabled)=>({id,label,players,rated:true,enabled,provisionalGames:5,defaultRating:1500,defaultRatingDeviation:350,notes:'safe'});
function modes(){return{modes:[common('standard_1v1','Standard','1v1',true),{...common('speed_1v1','Speed / Blitz','1v1',true),queueEnabled:true,rulesetVersion:'speed_1v1_v1_75s',readyLifecycleVersion:'speed_ready_v1_match_created_20s',ratingAlgorithmConfigVersion:'speed_1v1_glicko_v1',timeControl:{roundTimeSeconds:75,invitationWindowSeconds:90,readyWindowSeconds:20,readyWindowStartsOn:'first_valid_ready_acknowledgement',countdownSeconds:3,maxGuesses:6,solveTimeBucketMs:100,tieBreaker:'server_solve_time_bucket'}},common('classic_1v1','Classic','1v1',false),common('multiplayer_lobby','Multiplayer / Lobby','2-4',false)]};}
function envelope(data){const body={data,meta:{requestId:'request-255',timestamp:'2026-07-29T11:59:30.000Z'}};return{body,bodyBytes:Buffer.byteLength(JSON.stringify(body)),contentType:'application/json'};}
function publicAdapter(inv,mutate=()=>{}){const calls=[];return{calls,async get(url){calls.push(url);const path=new URL(url).pathname,preview=url.startsWith(inv.origins.previewApi);let base;if(path==='/healthz')base=envelope({status:'ok',service:'wordle-royale-api',environment:'production',timestamp:'2026-07-29T11:59:30.000Z',uptimeSeconds:1,revision:inv.deployments.apiRevision});else if(path==='/readyz')base=envelope(ready(inv,preview));else if(path==='/ranked/modes')base=envelope(modes());else {const dormant=inv.activationPhase==='dormant';const body={revision:inv.deployments.webRevision,appEnvironment:'production',mode:dormant?'disabled':'durable',registrationMode:dormant?null:inv.config.registrationMode};base={body,bodyBytes:Buffer.byteLength(JSON.stringify(body)),contentType:'application/json'};}const result={method:'GET',status:200,redirected:false,url,...base};mutate(result,path);return result;}};}
function completeSnapshot(change=false){const models=APPLICATION_MODEL_TABLES.map(([model,table],index)=>({model,table,count:index===0&&change?1:0,digest:(index===0&&change?'d':'c').repeat(64)}));return{schemaVersion:1,manifestDigest:APPLICATION_MANIFEST_DIGEST,modelCount:models.length,totalCount:change?1:0,stateDigest:receiptFor(models),models};}
function databaseAdapter(inv,{change=false,readOnly='on',observationReadOnly='on',extraMigration=false,host=hostFp,sql=[],snapshotOverride}={}){const execute=(observation)=>async(work)=>{await work(async statement=>{sql.push(statement);if(statement===PREFLIGHT_SQL.isolation)return true;if(statement===PREFLIGHT_SQL.readOnlyStatus)return{transactionReadOnly:observation?observationReadOnly:readOnly};if(statement===PREFLIGHT_SQL.snapshot)return snapshotOverride?.(observation)??completeSnapshot(observation&&change);if(statement===PREFLIGHT_SQL.migrations)return extraMigration?[...inv.migrations,{id:'unexpected',status:'applied'}]:inv.migrations;if(statement===PREFLIGHT_SQL.identity)return{identityFingerprint:inv.database.identityFingerprint,databaseHostFingerprint:host};if(statement===PREFLIGHT_SQL.schema)return{status:'ok',remediationConflictCount:0};throw new Error('bad sql');});};return{withReadOnlyTransaction:execute(false),withReadOnlyObservation:execute(true)};}
async function passedPreflight(){const inv=inventory();return runActivationPreflight({...authenticatedInputs(inv),publicAdapter:publicAdapter(inv),databaseAdapter:databaseAdapter(inv),now:()=>NOW});}

test('CLI adapters normalize only valid JSON media types while preserving invalid variants for core rejection',()=>{
  assert.equal(normalizeJsonContentType('application/json'), 'application/json');
  assert.equal(normalizeJsonContentType('Application/JSON; charset=UTF-8'), 'application/json');
  assert.equal(normalizeJsonContentType('application/json; profile="unexpected"'), 'application/json; profile="unexpected"');
  assert.equal(normalizeJsonContentType('text/json; charset=utf-8'), 'text/json; charset=utf-8');
  assert.equal(normalizeJsonContentType(null), null);
});

test('preflight binds authenticated provider provenance and complete snapshots',async()=>{const inv=inventory(),sql=[];const result=await runActivationPreflight({...authenticatedInputs(inv),publicAdapter:publicAdapter(inv),databaseAdapter:databaseAdapter(inv,{sql}),now:()=>NOW});assert.equal(result.receipt,receiptFor(result.evidence));assert.equal(result.evidence.activationPhase,'canary');assert.equal(result.evidence.proof.webIdentity,'ok');assert.equal(result.evidence.proof.providerDerived,true);assert.deepEqual(result.evidence.providerReceipt,providerReceipt);assert.deepEqual(result.evidence.providerInventory,providerInventory);assert.deepEqual(sql,[PREFLIGHT_SQL.isolation,PREFLIGHT_SQL.readOnlyStatus,PREFLIGHT_SQL.snapshot,PREFLIGHT_SQL.migrations,PREFLIGHT_SQL.identity,PREFLIGHT_SQL.schema,PREFLIGHT_SQL.isolation,PREFLIGHT_SQL.readOnlyStatus,PREFLIGHT_SQL.snapshot]);assert.equal(verifyPreflightReceipt(result,NOW).receipt,result.receipt);});
test('production providerDerived rejects fixture v2, downgrade, and absent explicit lane before probes',async()=>{const inv=inventory();let probes=0;const adapters={publicAdapter:{get:async()=>{probes++;}},databaseAdapter:{withReadOnlyTransaction:async()=>{probes++;},withReadOnlyObservation:async()=>{probes++;}},now:()=>NOW};for(const lane of [undefined,'production-live-v3','fixture-v2'])await assert.rejects(runActivationPreflight({...authenticatedInputs(inv,{providerEvidenceLane:lane}),...adapters}),/(production_provider_v3_required|provider_provenance_verification_failed)/);assert.equal(probes,0);});
test('provider authentication and operational identity binding fail before database/public work',async()=>{const inv=inventory();let gets=0,transactions=0;const adapters={publicAdapter:{get:async()=>{gets++;}},databaseAdapter:{withReadOnlyTransaction:async()=>{transactions++;},withReadOnlyObservation:async()=>{transactions++;}},now:()=>NOW};const cases=[{operationalInventory:inv,inventoryReceipt:receiptFor(inv)},authenticatedInputs(inv,{providerReceipt:receiptFor(providerInventory)}),authenticatedInputs(inv,{nativeEvidence:undefined}),authenticatedInputs(inv,{expectedNonce:'different-nonce'}),authenticatedInputs({...inv,provider:{...inv.provider,databaseId:'wrong-database'}}),authenticatedInputs({...inv,deployments:{...inv.deployments,apiDeploymentId:'wrong-deployment'}})];for(const input of cases)await assert.rejects(runActivationPreflight({...input,...adapters}),/(provider_|inventory_)/u);assert.equal(gets,0);assert.equal(transactions,0);});
test('inventory is exact, fresh, sanitized and separately receipted',()=>{const inv=inventory();assert.throws(()=>validateInventory({...inv,extra:true},NOW),/inventory_schema_invalid/);assert.throws(()=>validateInventory({...inv,source:{...inv.source,observedAt:'2026-07-29T13:00:00Z'}},NOW),/evidence_stale/);assert.throws(()=>validateInventory({...inv,expiresAt:'2026-07-29T11:00:00Z'},NOW),/evidence_stale/);assert.throws(()=>validateInventory({...inv,replicas:{...inv.replicas,observedReplicaId:undefined}},NOW));assert.throws(()=>parsePreflightArgs(['--inventory','x']),/arguments_invalid/);const live=['--provider-evidence-lane','production-live-v3','--operational-inventory','/inventory','--live-output-root','/output','--live-run-id','run-275','--challenge-policy','/policy','--collector-keyring','/keyring','--replay-root','/replay'];assert.equal(parsePreflightArgs(live).providerEvidenceLane,'production-live-v3');for(const extra of [['--now','1'],['--provider-inventory','/caller-inventory'],['--provider-receipt','/fixture-receipt']])assert.throws(()=>parsePreflightArgs([...live,...extra]),/arguments_invalid/);});
test('public probes reject redirect, wrong content type, oversized body, extras and web mismatch',async()=>{for(const [code,mutate] of [['public_redirect',(r)=>{r.redirected=true;r.status=302;}],['public_content_type_invalid',(r)=>{r.contentType='application/json; charset=utf-8';}],['public_body_oversized',(r)=>{r.bodyBytes=65537;}],['public_body_oversized',(r,p)=>{if(p==='/healthz'){r.body.data.padding='x'.repeat(70_000);r.bodyBytes=1;}}],['health_schema_invalid',(r,p)=>{if(p==='/healthz')r.body.data.extra=true;}],['web_revision_mismatch',(r,p)=>{if(p.includes('wordle-identity'))r.body.revision='f'.repeat(40);}]] ){const inv=inventory();await assert.rejects(runActivationPreflight({...authenticatedInputs(inv),publicAdapter:publicAdapter(inv,mutate),databaseAdapter:databaseAdapter(inv),now:()=>NOW}),new RegExp(code));}});
test('DB blockers reject extra migrations, host mismatch and transaction_read_only off',async()=>{for(const [code,opts] of [['migration_status_invalid',{extraMigration:true}],['database_host_mismatch',{host:'f'.repeat(64)}],['transaction_read_only_off',{readOnly:'off'}]]){const inv=inventory();await assert.rejects(runActivationPreflight({...authenticatedInputs(inv),publicAdapter:publicAdapter(inv),databaseAdapter:databaseAdapter(inv,opts),now:()=>NOW}),new RegExp(code));}});
test('dormant G3, closed, and canary phases enforce their exact API and web identities',async()=>{for(const phase of ['dormant','closed','canary']){const base=inventory(),inv=inventory({activationPhase:phase,config:{...base.config,durableAuth:phase!=='dormant',registrationMode:phase==='canary'?'canary':'closed'}});const result=await runActivationPreflight({...authenticatedInputs(inv),publicAdapter:publicAdapter(inv),databaseAdapter:databaseAdapter(inv),now:()=>NOW});assert.equal(result.evidence.activationPhase,phase);}});
test('wrong activation phase fails before probes and phase-inconsistent public identity fails closed',async()=>{const base=inventory(),wrong=inventory({activationPhase:'closed',config:{...base.config,durableAuth:true,registrationMode:'canary'}});let gets=0;await assert.rejects(runActivationPreflight({...authenticatedInputs(wrong),publicAdapter:{get:async()=>{gets++;}},databaseAdapter:databaseAdapter(wrong),now:()=>NOW}),/activation_phase_runtime_mismatch/);assert.equal(gets,0);const closed=inventory({activationPhase:'closed',config:{...base.config,registrationMode:'closed'}});await assert.rejects(runActivationPreflight({...authenticatedInputs(closed),publicAdapter:publicAdapter(closed,(response,path)=>{if(path.includes('wordle-identity'))response.body.registrationMode='canary';}),databaseAdapter:databaseAdapter(closed),now:()=>NOW}),/web_identity_phase_mismatch/);});
test('independent post-probe read-only observation detects concurrently visible GET writes',async()=>{const inv=inventory();await assert.rejects(runActivationPreflight({...authenticatedInputs(inv),publicAdapter:publicAdapter(inv),databaseAdapter:databaseAdapter(inv,{change:true}),now:()=>NOW}),/zero_write_observation_mismatch/);await assert.rejects(runActivationPreflight({...authenticatedInputs(inv),publicAdapter:publicAdapter(inv),databaseAdapter:databaseAdapter(inv,{observationReadOnly:'off'}),now:()=>NOW}),/observation_transaction_read_only_off/);});
test('complete snapshot detects count and update drift in every model and fails closed on manifest/query shapes',async()=>{const inv=inventory();for(let index=0;index<APPLICATION_MODEL_TABLES.length;index++){for(const operation of ['insert','delete','update']){const baseline=completeSnapshot();const after=structuredClone(baseline);if(operation==='insert'){after.models[index].count++;after.totalCount++;}else if(operation==='delete'){after.models[index].count=1;after.totalCount=1;baseline.models[index].count=2;baseline.totalCount=2;}after.models[index].digest=(index.toString(16).padStart(2,'0')).repeat(32);baseline.stateDigest=receiptFor(baseline.models);after.stateDigest=receiptFor(after.models);await assert.rejects(runActivationPreflight({...authenticatedInputs(inv),publicAdapter:publicAdapter(inv),databaseAdapter:databaseAdapter(inv,{snapshotOverride:(observation)=>observation?after:baseline}),now:()=>NOW}),/zero_write_observation_mismatch/);}}for(const corrupt of [(snapshot)=>{snapshot.models.pop();},(snapshot)=>{snapshot.manifestDigest='0'.repeat(64);},(snapshot)=>{snapshot.models[0].digest='unsafe';},(snapshot)=>{snapshot.stateDigest='0'.repeat(64);}]){const snapshot=completeSnapshot();corrupt(snapshot);await assert.rejects(runActivationPreflight({...authenticatedInputs(inv),publicAdapter:publicAdapter(inv),databaseAdapter:databaseAdapter(inv,{snapshotOverride:()=>snapshot}),now:()=>NOW}),/complete_fingerprint_/);}});
test('rollback contract keeps durable API active until the session operator revokes and proves zero',()=>{assert.deepEqual(validateRollbackOrder(ROLLBACK_ORDER),ROLLBACK_ORDER);for(const invalid of [[...ROLLBACK_ORDER].reverse(),ROLLBACK_ORDER.filter(x=>x!=='sessions-revoked'),['web-writes-off','api-durable-off','registration-closed','sessions-revoked','zero-active-sessions-proven','code-rollback']])assert.throws(()=>validateRollbackOrder(invalid),/rollback_order_invalid/);});
test('smoke rejects stale or tampered preflight before any network or reconciliation',async()=>{const pf=await passedPreflight(),secrets={email:'canary@example.test',password:'correct horse battery',handle:'canary_255',displayName:'Canary'},runId='smoke-run-255';const approval={schemaVersion:1,approvalId:'approval-255',runId,preflightReceipt:pf.receipt,artifactSha:pf.evidence.artifactSha,provider:pf.evidence.provider,deployments:pf.evidence.deployments,origins:{api:pf.evidence.origins.api,web:pf.evidence.origins.web},registrationMode:'canary',accountFingerprint:accountFingerprint(runId,secrets),approvedAt:'2026-07-29T11:59:00Z',expiresAt:'2026-07-29T12:20:00Z'};for(const bad of [{...pf,evidence:{...pf.evidence,database:{...pf.evidence.database,identityFingerprint:'f'.repeat(64)}}},{...pf,evidence:{...pf.evidence,expiresAt:'2026-07-29T11:00:00Z'},receipt:receiptFor({...pf.evidence,expiresAt:'2026-07-29T11:00:00Z'})}]){let network=0,db=0;const result=await runAuthActivationSmoke({approval:{...approval,preflightReceipt:bad.receipt},preflight:bad,secrets,transport:{request:async()=>{network++;}},reconciliation:{withReadOnlyTransaction:async()=>{db++;}},consumeApproval:async()=>{},now:()=>NOW});assert.equal(result.result,'FAIL');assert.equal(network,0);assert.equal(db,0);}assert.doesNotThrow(()=>validateApproval(approval,pf,secrets,NOW));});
test('smoke approval run ID is explicitly bound to the canary preflight run',async()=>{const pf=await passedPreflight(),secrets={email:'canary@example.test',password:'correct horse battery',handle:'canary_255',displayName:'Canary'},runId='different-smoke-run';const approval={schemaVersion:1,approvalId:'approval-255',runId,preflightReceipt:pf.receipt,artifactSha:pf.evidence.artifactSha,provider:pf.evidence.provider,deployments:pf.evidence.deployments,origins:{api:pf.evidence.origins.api,web:pf.evidence.origins.web},registrationMode:'canary',accountFingerprint:accountFingerprint(runId,secrets),approvedAt:'2026-07-29T11:59:00Z',expiresAt:'2026-07-29T12:20:00Z'};assert.throws(()=>validateApproval(approval,pf,secrets,NOW),/approval_run_id_mismatch/);});
test('smoke reconciliation fails closed when transaction_read_only is off',async()=>{const pf=await passedPreflight(),secrets={email:'canary@example.test',password:'correct horse battery',handle:'canary_255',displayName:'Canary'},runId='smoke-run-255';const approval={schemaVersion:1,approvalId:'approval-255',runId,preflightReceipt:pf.receipt,artifactSha:pf.evidence.artifactSha,provider:pf.evidence.provider,deployments:pf.evidence.deployments,origins:{api:pf.evidence.origins.api,web:pf.evidence.origins.web},registrationMode:'canary',accountFingerprint:accountFingerprint(runId,secrets),approvedAt:'2026-07-29T11:59:00Z',expiresAt:'2026-07-29T12:20:00Z'};let network=0;const result=await runAuthActivationSmoke({approval,preflight:pf,secrets,transport:{request:async()=>{network++;}},reconciliation:{async withReadOnlyTransaction(work){await work(async sql=>sql===SMOKE_RECONCILIATION_SQL.readOnlyStatus?{transactionReadOnly:'off'}:true);}},consumeApproval:async()=>{},now:()=>NOW});assert.equal(result.failureCode,'reconciliation_transaction_read_only_off');assert.equal(network,0);});
test('protected input and flags remain fail closed',async()=>{assert.throws(()=>parseSmokeArgs(['--email','x']),/sensitive_argument_forbidden/);await assert.rejects(readProtectedStdin(Readable.from(['{}']),{isTTY:true}),/stdin_tty_forbidden/);await assert.rejects(readProtectedStdin(Readable.from(['x'.repeat(5000)]),{isTTY:false}),/stdin_oversized/);});

const smokeSecrets={email:'canary@example.test',password:'correct horse battery',handle:'canary_255',displayName:'Canary'};
async function smokeFixture(){const preflight=await passedPreflight(),runId='smoke-run-255';return{preflight,secrets:{...smokeSecrets},approval:{schemaVersion:1,approvalId:'approval-255',runId,preflightReceipt:preflight.receipt,artifactSha:preflight.evidence.artifactSha,provider:preflight.evidence.provider,deployments:preflight.evidence.deployments,origins:{api:preflight.evidence.origins.api,web:preflight.evidence.origins.web},registrationMode:'canary',accountFingerprint:accountFingerprint(runId,smokeSecrets),approvedAt:'2026-07-29T11:59:00Z',expiresAt:'2026-07-29T12:20:00Z'}};}
const cookie=(value)=>`__Host-wr_session=${value}; Secure; HttpOnly; SameSite=Lax; Path=/; Max-Age=3600; Expires=Thu, 01 Jan 2027 00:00:00 GMT`;
const clearCookie=`__Host-wr_session=; Secure; HttpOnly; SameSite=Lax; Path=/; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT`;
const authError=(code,message,details={})=>({data:null,error:{code,message,details},requestId:'request-255'});
const success=(data)=>({data,error:null,requestId:'request-255'});
const token=(n)=>`wr1.${String(n).repeat(43)}`;
const emptySnapshot=()=>({accountCount:0,profileCount:0,credentialCount:0,consentCount:0,sessionCount:0,terminalSessionCount:0,activeSessionCount:0,accountIdentityFingerprint:'0'.repeat(64),nonTargetSessionCount:2,nonTargetSessionFingerprint:'7'.repeat(64),nonTargetAuthCount:4,nonTargetAuthFingerprint:'5'.repeat(64),nonTargetRateLimitCount:1,nonTargetRateLimitFingerprint:'4'.repeat(64),registerAttempts:0,loginAttempts:0,registerBucketCount:0,loginBucketCount:0,blockedBucketCount:0,lobbyWriteCount:0,speedWriteCount:0,ticketWriteCount:0,matchWriteCount:0,gameplayWriteCount:0,mutationWriteCount:0,ratingWriteCount:0,eventWriteCount:0,sharedStateFingerprint:'6'.repeat(64),sharedStateUnchanged:true,catalogFingerprint:'9'.repeat(64)});
const finalSnapshot=(fixture)=>({...emptySnapshot(),accountCount:1,profileCount:1,credentialCount:1,accountIdentityFingerprint:fixture.approval.accountFingerprint,sessionCount:3,terminalSessionCount:3,registerAttempts:2,loginAttempts:8,registerBucketCount:2,loginBucketCount:3});
function smokeAdapters(fixture,{mutateResponse=()=>{},finalOverride={},consume=()=>{},hangPath=null,deadlineCapMs=undefined}={}){
  const calls=[],timeline=[];let snapshots=0,session=0,active=null,rankedReads=0;
  const transport={calls,deadlineCapMs,async request(input){calls.push(structuredClone(input));timeline.push(`request:${new URL(input.url).pathname}`);const path=new URL(input.url).pathname;if(path===hangPath)return new Promise(()=>{});let status=200,body,setCookie=[],contentType='application/json';
    if(path==='/.well-known/wordle-identity')body={revision:fixture.approval.deployments.webRevision,appEnvironment:'production',mode:'durable',registrationMode:'canary'};
    else if(path==='/healthz')body=success({status:'ok'});
    else if(path==='/readyz')body=success({status:'ok',revision:fixture.approval.deployments.apiRevision,dependencies:{durableAuth:{status:'ok',registrationMode:'canary'}}});
    else if(path==='/ranked/modes'){rankedReads++;body=success(modes());}
    else if(path==='/auth/register'){status=201;session++;active=token(session);body=success({user:{id:'user-255'},session:{id:`session-${session}`}});setCookie=[cookie(active)];}
    else if(path==='/auth/logout'){active=null;status=204;body=null;contentType=null;setCookie=[clearCookie];}
    else if(path==='/auth/me'){if(input.cookie===`__Host-wr_session=${active}`&&active){body=success({id:'user-255'});}else{status=401;body=authError('not_authenticated','Sign in is required for this action.',{authMode:'session_required',appEnv:'production'});}}
    else if(path==='/auth/login'){
      if(input.origin!==fixture.approval.origins.web){status=403;body=authError('unsafe_request_origin','Request origin is not allowed.');}
      else if(typeof input.cookie==='string'&&(/(__Host-wr_session=.*; __Host-wr_session=)|(?:^|; )wr_session=|(?:^|; )wr_preview_demo_session=/u.test(input.cookie))){status=403;body=authError('unsafe_auth_cookie','Authentication cookie is not allowed.');}
      else if(input.json?.password!==fixture.secrets.password){status=401;body=authError('invalid_credentials','Invalid credentials.');}
      else{session++;active=token(session);body=success({user:{id:'user-255'},session:{id:`session-${session}`}});setCookie=[cookie(active)];}
    } else throw new Error(`unexpected path ${path}`);
    const record={method:input.method,url:input.url,effectiveUrl:input.url,origin:input.origin,redirect:input.redirect,status,contentType,bodyBytes:body===null?0:Buffer.byteLength(JSON.stringify(body)),setCookie,body,elapsedMs:10,attempts:1};
    mutateResponse(record,{input,path,index:calls.length-1,rankedReads});return record;}};
  const reconciliation={async withReadOnlyTransaction(work){const current=snapshots++===0?emptySnapshot():{...finalSnapshot(fixture),...finalOverride};await work(async(sql)=>sql===SMOKE_RECONCILIATION_SQL.readOnlyStatus?{transactionReadOnly:'on'}:sql===SMOKE_RECONCILIATION_SQL.snapshot?current:true);}};
  const consumeApproval=async(binding)=>{timeline.push('consume');consume(binding);};
  return{transport,reconciliation,consumeApproval,timeline};
}
async function executeSmoke(options={}){const fixture=await smokeFixture(),adapters=smokeAdapters(fixture,options);const result=await runAuthActivationSmoke({...fixture,...adapters,now:()=>NOW});return{fixture,adapters,result};}

test('pure smoke executes the exact lifecycle, three ambiguity probes, GET-only catalog snapshots, and consumes approval immediately before one register',async()=>{const{result,adapters}=await executeSmoke();assert.equal(result.result,'PASS');assert.equal(result.approvalConsumed,true);assert.equal(result.registerDispatches,1);assert.equal(result.sessionsCreated,3);assert.equal(result.retries,0);const receipted={...result};delete receipted.receipt;assert.equal(result.receipt,receiptFor(receipted));assert.equal(adapters.transport.calls.length,21);assert.deepEqual(adapters.transport.calls.filter(x=>new URL(x.url).pathname==='/ranked/modes').map(x=>x.method),['GET','GET']);assert.equal(adapters.transport.calls.filter(x=>new URL(x.url).pathname==='/auth/register').length,1);const registerIndex=adapters.timeline.indexOf('request:/auth/register');assert.equal(adapters.timeline[registerIndex-1],'consume');const cookies=adapters.transport.calls.filter(x=>typeof x.cookie==='string').map(x=>x.cookie);assert(cookies.some(x=>x.includes('; __Host-wr_session=')));assert(cookies.some(x=>x.includes('wr_session=opaque-insecure-probe')));assert(cookies.some(x=>x.includes('wr_preview_demo_session=')));assert(!canonicalJson(result).includes('canary@example.test'));assert(!canonicalJson(result).includes('wr1.'));});

test('smoke transport fails closed for missing records, unexpected cookies, redirects, authority/origin mismatch, content type and body bounds',async()=>{const cases=[
  ['transport_record_schema_invalid',(r,c)=>{if(c.index===0)delete r.setCookie;}],
  ['identity_set_cookie_invalid',(r,c)=>{if(c.index===0)r.setCookie=[cookie(token(8))];}],
  ['response_redirect',(r,c)=>{if(c.index===0)r.status=302;}],
  ['transport_response_authority_invalid',(r,c)=>{if(c.index===0)r.effectiveUrl='https://redirect.example.test/healthz';}],
  ['transport_request_identity_invalid',(r,c)=>{if(c.index===0)r.origin='https://other.example.test';}],
  ['response_content_type_invalid',(r,c)=>{if(c.index===0)r.contentType='application/json; charset=utf-8';}],
  ['response_body_oversized',(r,c)=>{if(c.index===0)r.bodyBytes=65537;}],
];for(const[code,mutateResponse]of cases){const{result}=await executeSmoke({mutateResponse});assert.equal(result.failureCode,code);}});

test('smoke rejects response envelope extras, token fields, extra and malformed production cookies',async()=>{const cases=[
  ['identity_envelope_invalid',(r,c)=>{if(c.index===0)r.body.extra=true;}],
  ['response_token_leak',(r,c)=>{if(c.path==='/auth/register')r.body.data.accessToken='secret';}],
  ['cookie_count_invalid',(r,c)=>{if(c.path==='/auth/register')r.setCookie.push('unexpected=1');}],
  ['cookie_shape_invalid',(r,c)=>{if(c.path==='/auth/register')r.setCookie=[`${r.setCookie[0]}; Domain=example.test`];}],
  ['clear_cookie_policy_invalid',(r,c)=>{if(c.path==='/auth/logout')r.setCookie=[r.setCookie[0].replace('Max-Age=0','Max-Age=1')];}],
];for(const[code,mutateResponse]of cases){const{result}=await executeSmoke({mutateResponse});assert.equal(result.failureCode,code);}});

test('smoke requires every ambiguity probe to return the generic rejection without auth mutation',async()=>{let changed=false;const{result}=await executeSmoke({mutateResponse(r,c){if(!changed&&c.path==='/auth/login'&&String(c.input.cookie).includes('wr_session=opaque-insecure-probe')){changed=true;r.status=200;r.body=success({user:{id:'user-255'},session:{id:'forbidden'}});r.bodyBytes=Buffer.byteLength(JSON.stringify(r.body));r.setCookie=[cookie(token(7))];}}});assert.equal(result.failureCode,'unsafe_auth_cookie_status_invalid');assert.equal(changed,true);});

test('smoke rejects account enumeration distinctions and ranked catalog changes',async()=>{let invalid=0;let run=await executeSmoke({mutateResponse(r,c){if(c.path==='/auth/login'&&r.status===401&&++invalid===2)r.body.error.message='Unknown account.';}});assert.equal(run.result.failureCode,'invalid_credentials_envelope_invalid');run=await executeSmoke({mutateResponse(r,c){if(c.path==='/ranked/modes'&&c.rankedReads===2)r.body.data.modes[0].enabled=false;}});assert.equal(run.result.failureCode,'catalog_mutation_detected');});

test('smoke reconciliation rejects hostile session cardinality, scoped limiter bounds, omitted writes, and fingerprint drift',async()=>{for(const[code,finalOverride]of[
  ['terminal_auth_cardinality_invalid',{sessionCount:2,terminalSessionCount:2}],
  ['terminal_auth_cardinality_invalid',{activeSessionCount:1,terminalSessionCount:2}],
  ['rate_limit_budget_invalid',{loginAttempts:9}],
  ['rate_limit_budget_invalid',{blockedBucketCount:1}],
  ['ranked_mutation_detected',{ticketWriteCount:1}],
  ['ranked_mutation_detected',{speedWriteCount:1}],
  ['ranked_mutation_detected',{mutationWriteCount:1}],
  ['ranked_mutation_detected',{eventWriteCount:1}],
  ['ranked_mutation_detected',{sharedStateUnchanged:false}],
  ['ranked_mutation_detected',{catalogFingerprint:'8'.repeat(64)}],
  ['terminal_auth_cardinality_invalid',{accountIdentityFingerprint:'8'.repeat(64)}],
  ['non_target_session_mutation_detected',{nonTargetSessionFingerprint:'8'.repeat(64)}],
  ['non_target_auth_mutation_detected',{nonTargetAuthFingerprint:'8'.repeat(64)}],
  ['non_target_rate_limit_mutation_detected',{nonTargetRateLimitFingerprint:'8'.repeat(64)}],
]){const{result}=await executeSmoke({finalOverride});assert.equal(result.failureCode,code);}});

test('fresh web identity drift fails before approval consumption and register dispatch',async()=>{let consumed=0;const{result,adapters}=await executeSmoke({consume(){consumed++;},mutateResponse(r,c){if(c.path==='/.well-known/wordle-identity')r.body.revision='f'.repeat(40);}});assert.equal(result.failureCode,'web_identity_recheck_failed');assert.equal(consumed,0);assert.equal(adapters.transport.calls.some((call)=>new URL(call.url).pathname==='/auth/register'),false);});

test('a hung registration is deadline-bounded with zero retries and leaves its approval consumed as ambiguous',async()=>{let consumed=0;const{result,adapters}=await executeSmoke({hangPath:'/auth/register',deadlineCapMs:20,consume(){consumed++;}});assert.equal(result.failureCode,'request_deadline_exceeded');assert.equal(result.approvalConsumed,true);assert.equal(result.registerDispatches,1);assert.equal(result.retries,0);assert.equal(consumed,1);assert.equal(adapters.transport.calls.filter((call)=>new URL(call.url).pathname==='/auth/register').length,1);});

test('account approval fingerprint binds email, handle and display name',async()=>{const fixture=await smokeFixture();for(const change of [{handle:'other_handle'},{displayName:'Other Canary'},{email:'other@example.test'}])assert.throws(()=>validateApproval(fixture.approval,fixture.preflight,{...fixture.secrets,...change},NOW),/approval_account_binding_mismatch/);});

test('durable approval consumption rejects replay, symlink and permissive directory modes',async()=>{const root=await mkdtemp(join(tmpdir(),'ticket263-consume-'));const binding={approvalId:'approval-263',runId:'run-263',preflightReceipt:'a'.repeat(64),accountFingerprint:'b'.repeat(64)};try{const directory=join(root,'receipts');const first=await consumeApprovalDurably(directory,binding);assert.match(first.consumptionReceipt,/^[a-f0-9]{64}$/u);const receiptStat=await stat(first.path);assert.equal(receiptStat.mode&0o777,0o600);if(typeof process.getuid==='function')assert.equal(receiptStat.uid,process.getuid());const persisted=JSON.parse(await readFile(first.path,'utf8'));assert.equal(persisted.consumptionReceipt,first.consumptionReceipt);await assert.rejects(consumeApprovalDurably(directory,binding),/EEXIST/);const permissive=join(root,'permissive');await consumeApprovalDurably(permissive,{...binding,approvalId:'approval-mode'});await chmod(permissive,0o755);await assert.rejects(consumeApprovalDurably(permissive,{...binding,approvalId:'approval-mode-2'}),/consumption_directory_permissions_invalid/);const target=join(root,'target');await consumeApprovalDurably(target,{...binding,approvalId:'approval-target'});const link=join(root,'link');await symlink(target,link);await assert.rejects(consumeApprovalDurably(link,{...binding,approvalId:'approval-link'}),/consumption_directory_invalid/);}finally{await rm(root,{recursive:true,force:true});}});
