import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync, createHash, verify } from 'node:crypto';
import { chmod, link, mkdtemp, mkdir, readFile, readdir, rename, rm, stat, symlink, writeFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { canonicalJson, sha256, retryConstants, PRIOR_APPROVAL_DIGEST, PRIOR_ATTEMPT_DIGEST } from './g0-retry-eligibility-core.mjs';
import { g0RetryCollectorPolicy, G0_RETRY_COLLECTOR_POLICY_DIGEST, G0_RETRY_ADAPTER_ENVELOPE_SCHEMA } from './g0-retry-evidence-collector-core.mjs';
import { G0_RETRY_BINDING_SCHEMA, G0_RETRY_ADAPTER_PLAN_SCHEMA } from './g0-retry-evidence-collector-production-core.mjs';
import { G0_RETRY_COMMIT_SCHEMA, openG0ProtectedDirectory, parseG0StrictJson, publishG0RetryBundle } from './g0-retry-evidence-collector-io.mjs';

const HERE=resolve(new URL('.',import.meta.url).pathname),CLI=join(HERE,'g0-retry-evidence-collector.mjs'),VALIDATOR=join(HERE,'g0-retry-eligibility.mjs'),HISTORY=join(HERE,'fixtures/g0-retry-sanitized-history'),CANARY='AJ2_PRIVATE_CANARY_DO_NOT_LEAK';
const run=(file,args,env={...process.env,AJ2_SECRET:CANARY})=>new Promise((ok,no)=>{const child=spawn(process.execPath,[file,...args],{stdio:['ignore','pipe','pipe'],env});let stdout='',stderr='';child.stdout.on('data',x=>stdout+=x);child.stderr.on('data',x=>stderr+=x);child.on('error',no);child.on('close',code=>ok({code,stdout,stderr}));});
const absent=kind=>({id:retryConstants.createdIds[kind],name:retryConstants.createdNames[kind],idLookup:'absent',nameLookup:'absent',pendingDeletion:false,tombstone:false});
async function put(path,value,mode=0o600){await writeFile(path,typeof value==='string'?value:`${JSON.stringify(value)}\n`,{mode});await chmod(path,mode);return path;}
async function fixture({blocked=false,adapterTransform}={}){
 const root=await mkdtemp(join(tmpdir(),'g0-aj2-'));await chmod(root,0o700);const input=join(root,'input'),output=join(root,'output'),replay=join(root,'collector-replay'),validatorOutput=join(root,'validator-output'),validatorReplay=join(root,'validator-replay');for(const x of [input,output,replay,validatorOutput,validatorReplay])await mkdir(x,{mode:0o700});
 const qualification=JSON.parse(await readFile(join(HISTORY,'merged-local-qualification.json'))),priorApproval=JSON.parse(await readFile(join(HISTORY,'consumed-single-use-approval.json'))),priorAttempt=JSON.parse(await readFile(join(HISTORY,'rolled-back-attempt.json')));const now=Date.now(),issued=new Date(now-20_000).toISOString(),expires=new Date(now+100_000).toISOString(),observed=new Date(now-5_000).toISOString();
 const {privateKey,publicKey}=generateKeyPairSync('ed25519'),keyId='collector-key-aj2-001',challenge={schemaVersion:'wordle-royale-g0-retry-challenge/v1',challengeId:'challenge-aj2-001',runId:'run-aj2-001',nonce:'nonce-aj2-001',issuedAt:issued,expiresAt:expires,collectorKeyId:keyId,qualification:{receiptDigest:qualification.receiptDigest,targetSha:qualification.targetSha,sourceArtifactDigest:qualification.sourceArtifactDigest,manifestDigest:qualification.manifestDigest,providerDefaultPolicyDigest:qualification.providerDefaultPolicyDigest},priorConsumedApproval:{approvalId:priorApproval.approvalId,artifactDigest:PRIOR_APPROVAL_DIGEST},priorAttempt:{artifactDigest:PRIOR_ATTEMPT_DIGEST},expectedCreatedResources:Object.fromEntries(Object.keys(retryConstants.createdIds).map(k=>[k,{id:retryConstants.createdIds[k],name:retryConstants.createdNames[k]}])),expectedPreviewIds:{...retryConstants.preview}};
 const challengeDigest=sha256(canonicalJson(challenge)),binding={schemaVersion:G0_RETRY_BINDING_SCHEMA,expectedChallengeId:challenge.challengeId,expectedRunId:challenge.runId,expectedNonce:challenge.nonce,expectedCollectorKeyId:keyId,challengeDigest,policyDigest:G0_RETRY_COLLECTOR_POLICY_DIGEST,maxLifetimeMs:180_000,now:new Date(now).toISOString()};
 const common=provider=>({schemaVersion:G0_RETRY_ADAPTER_ENVELOPE_SCHEMA,provider,adapterVersion:`synthetic-${provider}/1`,challengeId:challenge.challengeId,runId:challenge.runId,nonce:challenge.nonce,collectorKeyId:keyId,challengeDigest,policyDigest:G0_RETRY_COLLECTOR_POLICY_DIGEST,observedAt:observed,observationMode:'provider_control_plane_read_only',providerMutationObserved:false,status:'observed',blocker:null});const interval={start:'2026-08-01T00:00:00.000Z',end:'2026-09-01T00:00:00.000Z'};
 const envelopes={vercel:{...common('vercel'),payload:{account:{...g0RetryCollectorPolicy.accounts.vercel},billingInterval:interval,chargeQuotes:[{currency:'USD',interval,chargeUsd:'0'}],priorCreatedResource:absent('vercelProject'),preview:{projectId:retryConstants.preview.vercelProjectId,unchanged:true}}},railway:{...common('railway'),payload:{account:{...g0RetryCollectorPolicy.accounts.railway},billingInterval:interval,costQuotes:[{currency:'USD',interval,subtotalUsd:'4.9000',taxesUsd:'0.0100',feesUsd:'0.0100',appliedCreditsUsd:'0',unappliedBalanceUsd:'100'}],priorCreatedResources:Object.fromEntries(['railwayProject','railwayEnvironment','railwayService','railwayServiceInstance'].map(k=>[k,absent(k)])),preview:{projectId:retryConstants.preview.railwayProjectId,environmentId:retryConstants.preview.railwayEnvironmentId,serviceId:retryConstants.preview.railwayServiceId,unchanged:true}}},supabase:{...common('supabase'),payload:{preview:{projectRef:retryConstants.preview.postgresqlProjectRef,unchanged:true}}}};
 if(blocked)for(const [p,c] of [['vercel','VERCEL_BILLING_COMPLETENESS_UNAVAILABLE'],['railway','RAILWAY_TAX_OR_FEE_UNKNOWN'],['supabase','SUPABASE_AUTH_UNAVAILABLE']])Object.assign(envelopes[p],{status:'blocked',blocker:{code:c},payload:null});
 const adapters={};for(const provider of Object.keys(envelopes)){const path=join(input,`${provider}-adapter.mjs`),version=`synthetic-${provider}/1`;let source=`#!/usr/bin/node\nif(Object.keys(process.env).sort().join(',')!=='LANG,LC_ALL,PATH,TZ')process.exit(90);const a=process.argv.slice(2);if(a.length!==17||a[0]!=='collect'||a[a.indexOf('--provider')+1]!==${JSON.stringify(provider)}||a.at(-2)!=='--format'||a.at(-1)!=='json'||process.argv.includes(${JSON.stringify(CANARY)}))process.exit(91);process.stdout.write(${JSON.stringify(JSON.stringify(envelopes[provider]))});\n`;if(adapterTransform)source=adapterTransform(provider,source,envelopes[provider]);await put(path,source,0o500);adapters[provider]={provider,version,executable:{path,realpath:path,sha256:`sha256:${createHash('sha256').update(source).digest('hex')}`,version}};}
 const plan={schemaVersion:G0_RETRY_ADAPTER_PLAN_SCHEMA,challengeId:challenge.challengeId,runId:challenge.runId,nonce:challenge.nonce,collectorKeyId:keyId,challengeDigest,policyDigest:G0_RETRY_COLLECTOR_POLICY_DIGEST,adapters,limits:{timeoutMs:3000,totalTimeoutMs:15000,stdoutBytes:262144,stderrBytes:4096}},keyring={schemaVersion:'wordle-provider-collector-keyring/v1',keys:[{keyId,publicKeyPem:publicKey.export({format:'pem',type:'spki'}).toString(),notBefore:new Date(now-3600_000).toISOString(),notAfter:new Date(now+3600_000).toISOString(),revokedAt:null}]};
 const values={qualification,'prior-approval':priorApproval,'prior-attempt':priorAttempt,challenge,'policy-binding':binding,keyring,'adapter-plan':plan},files={};for(const [k,v] of Object.entries(values))files[k]=await put(join(input,`${k}.json`),v);files['signing-key']=await put(join(input,'private-key.pem'),privateKey.export({format:'pem',type:'pkcs8'}).toString());files['public-key']=await put(join(input,'public-key.pem'),publicKey.export({format:'pem',type:'spki'}).toString());const args=['qualification','prior-approval','prior-attempt','challenge','policy-binding','signing-key','keyring','adapter-plan'].flatMap(k=>[`--${k}`,files[k]]).concat(['--output-dir',output,'--collector-replay-dir',replay]);return{root,input,output,replay,validatorOutput,validatorReplay,files,args,challenge,binding,cleanup:()=>rm(root,{recursive:true,force:true})};
}

async function rewriteAdapter(s,provider,replacement,limits={}){const plan=JSON.parse(await readFile(s.files['adapter-plan'],'utf8')),path=plan.adapters[provider].executable.path;let source=await readFile(path,'utf8');source=source.replace(/process\.stdout\.write\(.+\);/u,match=>typeof replacement==='function'?replacement(match):replacement);await chmod(path,0o700);await writeFile(path,source);await chmod(path,0o500);plan.adapters[provider].executable.sha256=`sha256:${createHash('sha256').update(source).digest('hex')}`;Object.assign(plan.limits,limits);await writeFile(s.files['adapter-plan'],`${JSON.stringify(plan)}\n`,{mode:0o600});}
const empty=async s=>{assert.deepEqual(await readdir(s.output),[]);assert.deepEqual(await readdir(s.replay),[]);};

test('shipped collector runs three standalone pinned adapters and shipped validator proves committed bundle',async()=>{const s=await fixture();try{const r=await run(CLI,s.args);assert.equal(r.code,0,r.stderr);assert.equal(r.stderr,'');assert.equal(r.stdout.includes(CANARY),false);const response=JSON.parse(r.stdout);assert.equal(response.decision,'eligible_to_request_fresh_approval');assert.equal(response.freshApprovalRequired,true);assert.equal(response.hostedMutationAuthorized,false);assert.deepEqual((await readdir(s.output)).sort(),['challenge.json','commit-manifest.json','eligibility-preview.json','evidence.json','provider-receipt.json']);for(const name of await readdir(s.output))assert.equal((await stat(join(s.output,name))).mode&0o777,0o600);const validatorReceipt=join(s.validatorOutput,'eligibility.json'),a=['--qualification',s.files.qualification,'--prior-approval',s.files['prior-approval'],'--prior-attempt',s.files['prior-attempt'],'--challenge',response.files.challenge,'--evidence',response.files.evidence,'--provider-receipt',response.files.providerReceipt,'--collector-public-key',s.files['public-key'],'--expected-challenge-id',s.binding.expectedChallengeId,'--expected-run-id',s.binding.expectedRunId,'--expected-nonce',s.binding.expectedNonce,'--expected-collector-key-id',s.binding.expectedCollectorKeyId,'--replay-dir',s.validatorReplay,'--output',validatorReceipt];const verified=await run(VALIDATOR,a);assert.equal(verified.code,0,verified.stderr);assert.equal(JSON.parse(verified.stdout).decision,'eligible_to_request_fresh_approval');assert.notEqual(s.replay,s.validatorReplay);}finally{await s.cleanup();}});

test('strict adapter JSON rejects duplicate keys, trailing data, excessive depth, and invalid UTF-8',()=>{for(const bytes of [Buffer.from('{"a":1,"a":2}'),Buffer.from('{} trailing'),Buffer.from(`${'['.repeat(33)}0${']'.repeat(33)}`),Buffer.from([0xff])])assert.throws(()=>parseG0StrictJson(bytes));});

test('blocked current-live fixture and malformed adapter produce no trusted bundle or burned replay',async t=>{for(const [name,options,code] of [['blocked',{blocked:true},'CURRENT_LIVE_BLOCKED'],['malformed',{adapterTransform:(p,s)=>p==='vercel'?s.replace(/process\.stdout\.write\(.+\);/u,"process.stdout.write('{bad');"):s},'JSON_SYNTAX']])await t.test(name,async()=>{const s=await fixture(options);try{const r=await run(CLI,s.args);assert.equal(r.code,2,r.stderr);assert.equal(JSON.parse(r.stderr).code,code);assert.deepEqual(await readdir(s.output),[]);assert.deepEqual(await readdir(s.replay),[]);assert.equal((r.stderr+r.stdout).includes(CANARY),false);}finally{await s.cleanup();}});});

test('protected plan binding and adapter provider/binding/time mismatches fail before publication',async t=>{const planCases=[
 ['plan-challenge',p=>p.challengeId='other','ADAPTER_PLAN_BINDING_MISMATCH'],
 ['plan-provider',p=>p.adapters.vercel.provider='railway','ADAPTER_PLAN_INVALID'],
 ['plan-version',p=>p.adapters.vercel.executable.version='other','ADAPTER_VERSION_MISMATCH'],
 ['plan-path-alias',p=>p.adapters.railway.executable.path=p.adapters.vercel.executable.path,'ADAPTER_EXECUTABLE_ALIAS'],
];for(const [name,change,code] of planCases)await t.test(name,async()=>{const s=await fixture();try{const plan=JSON.parse(await readFile(s.files['adapter-plan']));change(plan);await put(s.files['adapter-plan'],plan);const r=await run(CLI,s.args);assert.equal(r.code,2,r.stderr);assert.equal(JSON.parse(r.stderr).code,code);await empty(s);}finally{await s.cleanup();}});const envelopeCases=[
 ['provider',x=>x.provider='railway','ADAPTER_PROVIDER_MISMATCH'],
 ['operation-binding',x=>x.runId='other','ADAPTER_BINDING_MISMATCH'],
 ['future-time',(x,s)=>x.observedAt=new Date(Date.parse(s.binding.now)+1).toISOString(),'ADAPTER_TIME_OUTSIDE_WINDOW'],
];for(const [name,change,code] of envelopeCases)await t.test(name,async()=>{let state;const s=await fixture({adapterTransform:(p,source,envelope)=>{if(p!=='vercel')return source;const x=structuredClone(envelope);change(x,state??{binding:{now:new Date().toISOString()}});return source.replace(JSON.stringify(JSON.stringify(envelope)),JSON.stringify(JSON.stringify(x)));}});state=s;try{if(name==='future-time'){const plan=JSON.parse(await readFile(s.files['adapter-plan']));const path=plan.adapters.vercel.executable.path;let source=await readFile(path,'utf8'),embedded=source.match(/process\.stdout\.write\((".*")\);/u);const x=JSON.parse(JSON.parse(embedded[1]));x.observedAt=new Date(Date.parse(s.binding.now)+1).toISOString();source=source.replace(embedded[1],JSON.stringify(JSON.stringify(x)));await chmod(path,0o700);await writeFile(path,source);await chmod(path,0o500);plan.adapters.vercel.executable.sha256=`sha256:${createHash('sha256').update(source).digest('hex')}`;await put(s.files['adapter-plan'],plan);}const r=await run(CLI,s.args);assert.equal(r.code,2,r.stderr);assert.equal(JSON.parse(r.stderr).code,code);await empty(s);}finally{await s.cleanup();}});});

test('protected inputs reject symlink, hardlink, permissive mode, and aliases without replay',async t=>{const cases=[
 ['symlink',async s=>{const real=`${s.files.challenge}.real`;await rename(s.files.challenge,real);await symlink(real,s.files.challenge);},'UNSAFE_INPUT_FILE'],
 ['hardlink',s=>link(s.files.keyring,`${s.files.keyring}.hard`),'UNSAFE_INPUT_FILE'],
 ['mode',s=>chmod(s.files['policy-binding'],0o640),'UNSAFE_INPUT_FILE'],
 ['alias',async s=>{s.args=[...s.args];s.args[s.args.indexOf('--signing-key')+1]=s.files.challenge;},'INPUT_FILE_ALIAS'],
];for(const [name,change,code] of cases)await t.test(name,async()=>{const s=await fixture();try{await change(s);const r=await run(CLI,s.args);assert.equal(r.code,code==='UNSAFE_INPUT_FILE'?4:2,r.stderr);assert.equal(r.stdout,'');assert.equal(JSON.parse(r.stderr).code,code);await empty(s);}finally{await s.cleanup();}});});

test('private/public key mismatch is rejected before adapter execution and replay',async()=>{const s=await fixture();try{const {privateKey}=generateKeyPairSync('ed25519');await put(s.files['signing-key'],privateKey.export({format:'pem',type:'pkcs8'}).toString());const r=await run(CLI,s.args);assert.equal(r.code,2,r.stderr);assert.deepEqual(JSON.parse(r.stderr),{ok:false,code:'COLLECTOR_KEY_MISMATCH'});await empty(s);}finally{await s.cleanup();}});

test('output collision, replay, and concurrent nonce reservation are fail-closed',async()=>{const s=await fixture();try{await put(join(s.output,'evidence.json'),'occupied');let r=await run(CLI,s.args);assert.equal(r.code,4,r.stderr);assert.equal(JSON.parse(r.stderr).code,'OUTPUT_ALREADY_EXISTS');assert.deepEqual(await readdir(s.replay),[]);await rm(join(s.output,'evidence.json'));r=await run(CLI,s.args);assert.equal(r.code,0,r.stderr);const other=join(s.root,'other-output');await mkdir(other,{mode:0o700});const otherArgs=[...s.args];otherArgs[otherArgs.indexOf('--output-dir')+1]=other;r=await run(CLI,otherArgs);assert.equal(r.code,3,r.stderr);assert.equal(JSON.parse(r.stderr).code,'CHALLENGE_REPLAY');assert.deepEqual(await readdir(other),[]);}finally{await s.cleanup();}const c=await fixture();try{const other=join(c.root,'concurrent');await mkdir(other,{mode:0o700});const args=[...c.args];args[args.indexOf('--output-dir')+1]=other;const results=await Promise.all([run(CLI,c.args),run(CLI,args)]);assert.deepEqual(results.map(x=>x.code).sort((a,b)=>a-b),[0,3]);assert.equal((await readdir(c.output)).length+(await readdir(other)).length,5);assert.equal(results.map(x=>x.stdout+x.stderr).join('').includes(CANARY),false);}finally{await c.cleanup();}});

test('executable symlink, hardlink, mode, hash drift, and live replacement are rejected',async t=>{const initial=[
 ['symlink',async(s,p)=>{const real=`${p}.real`;await rename(p,real);await symlink(real,p);},'EXECUTABLE_POLICY_MISMATCH'],
 ['hardlink',(s,p)=>link(p,`${p}.hard`),'EXECUTABLE_POLICY_MISMATCH'],
 ['mode',(s,p)=>chmod(p,0o700),'EXECUTABLE_POLICY_MISMATCH'],
 ['hash',async(s,p)=>{await chmod(p,0o700);await writeFile(p,`${await readFile(p)}\n// drift`);await chmod(p,0o500);},'EXECUTABLE_POLICY_MISMATCH'],
];for(const [name,change,code] of initial)await t.test(name,async()=>{const s=await fixture();try{const plan=JSON.parse(await readFile(s.files['adapter-plan'])),p=plan.adapters.vercel.executable.path;await change(s,p);const r=await run(CLI,s.args);assert.equal(r.code,2,r.stderr);assert.equal(JSON.parse(r.stderr).code,code);await empty(s);}finally{await s.cleanup();}});for(const name of ['inode','mode','hash'])await t.test(`live-${name}`,async()=>{const s=await fixture();try{const plan=JSON.parse(await readFile(s.files['adapter-plan'])),p=plan.adapters.vercel.executable.path;const action=name==='inode'?`const f=await import('node:fs/promises');await f.rename(${JSON.stringify(p)},${JSON.stringify(`${p}.old`)});await f.copyFile(${JSON.stringify(`${p}.old`)},${JSON.stringify(p)});await f.chmod(${JSON.stringify(p)},0o500);`:name==='mode'?`await import('node:fs/promises').then(f=>f.chmod(${JSON.stringify(p)},0o700));`:`const f=await import('node:fs/promises');await f.chmod(${JSON.stringify(p)},0o700);await f.appendFile(${JSON.stringify(p)},'\\n// changed');await f.chmod(${JSON.stringify(p)},0o500);`;await rewriteAdapter(s,'vercel',original=>`${original}${action}`);const r=await run(CLI,s.args);assert.equal(r.code,2,r.stderr);assert.equal(JSON.parse(r.stderr).code,name==='mode'?'EXECUTABLE_POLICY_MISMATCH':'EXECUTABLE_CHANGED');await empty(s);}finally{await s.cleanup();}});});

test('adapter timeout, nonzero, stdout, and stderr limits are sanitized and do not consume replay',async t=>{const cases=[
 ['nonzero','process.stderr.write(process.env.AJ2_SECRET??"hidden");process.exit(17);',{},'ADAPTER_NONZERO_EXIT'],
 ['timeout','await new Promise(r=>setTimeout(r,1000));',{timeoutMs:100},'PROCESS_TIMEOUT'],
 ['stdout','process.stdout.write("x".repeat(2048));',{stdoutBytes:256},'STDOUT_LIMIT'],
 ['stderr',original=>`process.stderr.write('x'.repeat(2048));${original}`,{stderrBytes:64},'STDERR_LIMIT'],
];for(const [name,source,limits,code] of cases)await t.test(name,async()=>{const s=await fixture();try{await rewriteAdapter(s,'vercel',source,limits);const r=await run(CLI,s.args);assert.equal(r.code,2,r.stderr);assert.equal(r.stdout,'');assert.deepEqual(JSON.parse(r.stderr),{ok:false,code});assert.equal(r.stderr.includes(CANARY),false);await empty(s);}finally{await s.cleanup();}});});

test('shared subreaper kills detached setsid descendants and pipe holders before response',async t=>{const cases=[
 ['timeout',false,(marker)=>`const{spawn}=await import('node:child_process');spawn('/usr/bin/node',['-e',${JSON.stringify(`setTimeout(()=>require('fs').writeFileSync('MARK','escaped'),500)`.replace('MARK',marker))}],{detached:true,stdio:'ignore'}).unref();await new Promise(r=>setTimeout(r,1000));`,{timeoutMs:100}],
 ['setsid-pipe',true,(marker,original)=>`const{spawn}=await import('node:child_process');spawn('/usr/bin/node',['-e',${JSON.stringify(`process.on('SIGTERM',()=>{});setTimeout(()=>require('fs').writeFileSync('MARK','escaped'),500)`.replace('MARK',marker))}],{detached:true,stdio:['ignore',1,2]}).unref();${original}`,{}],
];for(const [name,success,source,limits] of cases)await t.test(name,async()=>{const s=await fixture(),marker=join(s.root,`${name}.marker`);try{await rewriteAdapter(s,'vercel',original=>source(marker,original),limits);const r=await run(CLI,s.args);assert.equal(r.code,success?0:2,r.stderr);if(!success)assert.equal(JSON.parse(r.stderr).code,'PROCESS_TIMEOUT');await new Promise(x=>setTimeout(x,750));await assert.rejects(readFile(marker),'detached descendant escaped');if(!success)await empty(s);}finally{await s.cleanup();}});});

async function transactionFixture(){const root=await mkdtemp(join(tmpdir(),'g0-aj2-tx-')),output=join(root,'output'),replay=join(root,'replay');await mkdir(output,{mode:0o700});await mkdir(replay,{mode:0o700});const outputRoot=await openG0ProtectedDirectory(output),replayRoot=await openG0ProtectedDirectory(replay);return{root,output,replay,outputRoot,replayRoot,bundle:{challenge:{runId:`tx-${process.pid}-${Math.random()}`,nonce:`nonce-${process.pid}-${Math.random()}`},evidence:{x:1},providerReceipt:{x:2},eligibilityPreview:{x:3}},async cleanup(){await outputRoot.handle.close();await replayRoot.handle.close();await rm(root,{recursive:true,force:true});}};}
test('commit-last publication rolls back late failures, collisions, and root replacement',async t=>{const cases=[
 ['late-collision','candidates-ready',(s,c)=>writeFile(join(s.output,c.names.evidence),'occupied',{mode:0o600})],
 ['candidate-hardlink','candidates-ready',async s=>{const name=(await readdir(s.output)).find(x=>x.endsWith('.candidate'));await link(join(s.output,name),join(s.root,'candidate-hardlink'));}],
 ['output-root-replacement','candidates-ready',async s=>{await rename(s.output,`${s.output}.moved`);await mkdir(s.output,{mode:0o700});}],
 ['replay-root-replacement','candidates-ready',async s=>{await rename(s.replay,`${s.replay}.moved`);await mkdir(s.replay,{mode:0o700});}],
 ['final-hardlink','commit-published',(s,c)=>link(join(s.output,c.names.evidence),join(s.root,'final-hardlink'))],
 ['commit-removal','commit-published',(s,c)=>rm(join(s.output,c.commit))],
 ['late-commit-failure','commit-published',()=>{throw Object.assign(new Error('late'),{code:'LATE_FAILURE'});}],
];for(const [name,stage,attack] of cases)await t.test(name,async()=>{const s=await transactionFixture();try{await assert.rejects(publishG0RetryBundle({outputRoot:s.outputRoot,replayRoot:s.replayRoot,bundle:s.bundle,transactionHook:async(current,context)=>{if(current===stage)await attack(s,context);}}));for(const dir of [s.output,`${s.output}.moved`])try{const files=await readdir(dir);assert.equal(files.includes('commit-manifest.json'),false,files.join(','));assert.equal(files.some(x=>['challenge.json','evidence.json','provider-receipt.json','eligibility-preview.json'].includes(x)),false,files.join(','));}catch{}}finally{await s.cleanup();}});});

test('signatures and commit manifest bind exact bytes; tampering is detected',async()=>{const s=await fixture();try{const r=await run(CLI,s.args);assert.equal(r.code,0,r.stderr);const response=JSON.parse(r.stdout),publicPem=await readFile(s.files['public-key']);for(const component of ['evidence','providerReceipt']){const value=JSON.parse(await readFile(response.files[component])),unsigned={...value};delete unsigned.signature;assert.equal(verify(null,Buffer.from(canonicalJson(unsigned)),publicPem,Buffer.from(value.signature.slice(8),'base64')),true);}const manifest=JSON.parse(await readFile(response.commit));assert.equal(manifest.schemaVersion,G0_RETRY_COMMIT_SCHEMA);for(const [name,digest] of Object.entries(manifest.files))assert.equal(sha256(await readFile(join(s.output,name))),digest);const evidence=JSON.parse(await readFile(response.files.evidence));evidence.observedAt=new Date(Date.parse(evidence.observedAt)+1).toISOString();await writeFile(response.files.evidence,`${JSON.stringify(evidence)}\n`,{mode:0o600});assert.notEqual(sha256(await readFile(response.files.evidence)),manifest.files['evidence.json']);const receipt=join(s.validatorOutput,'tampered.json'),a=['--qualification',s.files.qualification,'--prior-approval',s.files['prior-approval'],'--prior-attempt',s.files['prior-attempt'],'--challenge',response.files.challenge,'--evidence',response.files.evidence,'--provider-receipt',response.files.providerReceipt,'--collector-public-key',s.files['public-key'],'--expected-challenge-id',s.binding.expectedChallengeId,'--expected-run-id',s.binding.expectedRunId,'--expected-nonce',s.binding.expectedNonce,'--expected-collector-key-id',s.binding.expectedCollectorKeyId,'--replay-dir',s.validatorReplay,'--output',receipt];const rejected=await run(VALIDATOR,a);assert.notEqual(rejected.code,0);assert.equal((rejected.stdout+rejected.stderr).includes(CANARY),false);}finally{await s.cleanup();}});

test('strace proves CLI, three pinned supervisors, three adapters, and no socket/connect',async t=>{try{await stat('/usr/bin/strace');}catch{t.skip('strace unavailable');return;}const s=await fixture(),trace=join(s.root,'trace.log');try{const result=await new Promise((ok,no)=>{const child=spawn('/usr/bin/strace',['-f','-e','trace=execve,connect,socket','-o',trace,process.execPath,CLI,...s.args],{stdio:['ignore','pipe','pipe'],env:{...process.env,AJ2_SECRET:CANARY}});let stderr='';child.stderr.on('data',x=>stderr+=x);child.on('error',no);child.on('close',code=>ok({code,stderr}));});assert.equal(result.code,0,result.stderr);const traced=await readFile(trace,'utf8');assert.equal((traced.match(/execve\(/gu)??[]).length,7,traced);assert.equal(/socket\(|connect\(/u.test(traced),false,traced);}finally{await s.cleanup();}});

test('production boundary is transport-free and pins the shared supervisor and interpreter',async()=>{for(const name of ['g0-retry-evidence-collector.mjs','g0-retry-evidence-collector-production-core.mjs','g0-retry-evidence-collector-io.mjs','g0-retry-evidence-collector-runner.mjs']){const source=await readFile(join(HERE,name),'utf8');assert.equal(source.includes('node:child_process'),name.endsWith('-runner.mjs'));assert.equal(/from ['"](?:node:)?(?:http2?|https|net|tls|dgram|dns)|from ['"](?:pg|postgres|vercel|railway|supabase)/u.test(source),false,name);}const runner=await readFile(join(HERE,'g0-retry-evidence-collector-runner.mjs'),'utf8'),helper=await readFile(join(HERE,'g2-adapter-supervisor.py'));assert.match(runner,/SUPERVISOR_SHA='sha256:[0-9a-f]{64}'/u);assert.match(runner,/PYTHON='\/usr\/bin\/python3'/u);assert.match(runner,/\['-I','-S','-B','\/proc\/self\/fd\/3'\]/u);assert.equal(`sha256:${createHash('sha256').update(helper).digest('hex')}`,runner.match(/SUPERVISOR_SHA='([^']+)'/u)[1]);});
