import assert from 'node:assert/strict';
import { createHash, generateKeyPairSync, verify } from 'node:crypto';
import { chmod, link, mkdir, mkdtemp, readFile, readdir, rename, rm, stat, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { spawn } from 'node:child_process';
import test from 'node:test';
import { buildSyntheticG2Bundle } from './g2-backup-restore-synthetic-fixture.mjs';
import { G2_ADAPTER_ENVELOPE_SCHEMA, G2_OPERATION_PLAN_SCHEMA, G2_SEMANTIC_OPERATIONS } from './g2-backup-restore-evidence-collector-core.mjs';
import { deriveG2BackupRestoreInventory, evaluateG2BackupRestoreReadiness, g2CanonicalJson, g2Sha256 } from './g2-backup-restore-readiness-core.mjs';
import { openG2ProtectedDirectory, publishG2CollectorBundle } from './g2-backup-restore-evidence-collector-io.mjs';

const HERE=dirname(new URL(import.meta.url).pathname),CLI=resolve(HERE,'g2-backup-restore-evidence-collector.mjs'),AH=resolve(HERE,'g2-backup-restore-readiness.mjs');
const CANARY='AI2_PRIVATE_SECRET_CANARY_NEVER_PRINT';
const payloadField={'provider-policy-observation':'providerPolicyObservation','rpo-rto-measurement':'rpoRtoMeasurement','completed-backup-artifact':'backupArtifact','isolated-restore-drill':'restoreDrill','production-no-mutation':'productionNoMutation','cleanup-absence-observation':'cleanup','retention-observation':'retention'};
const shift=(x,d)=>new Date(Date.parse(x)+d).toISOString();
function run(file,args,env={}){return new Promise((accept,reject)=>{const child=spawn(process.execPath,[file,...args],{shell:false,stdio:['ignore','pipe','pipe'],env:{...process.env,...env,AI2_SECRET:CANARY}}),out=[],err=[];const timer=setTimeout(()=>{child.kill('SIGKILL');reject(new Error('watchdog'));},20_000);child.stdout.on('data',x=>out.push(x));child.stderr.on('data',x=>err.push(x));child.on('error',reject);child.on('close',code=>{clearTimeout(timer);accept({code,stdout:Buffer.concat(out).toString(),stderr:Buffer.concat(err).toString()});});});}
async function fixture(){
 const root=await mkdtemp(join(tmpdir(),'g2-ai2-')),protectedDir=join(root,'protected'),output=join(root,'output'),collectorReplay=join(root,'collector-replay'),ahOutput=join(root,'ah-output'),ahReplay=join(root,'ah-replay');await Promise.all([protectedDir,output,collectorReplay,ahOutput,ahReplay].map(x=>mkdir(x,{mode:0o700})));
 const {privateKey,publicKey}=generateKeyPairSync('ed25519'),suffix=`${process.pid}-${Math.random().toString(16).slice(2)}`;const bundle=buildSyntheticG2Bundle({signCanonical:()=>`ed25519:${Buffer.alloc(64).toString('base64')}`,challengeId:`challenge-ai2-${suffix}`,runId:`run-ai2-${suffix}`,nonce:`nonce-ai2-${suffix}`,collectorKeyId:`key-ai2-${suffix}`});
 const delta=(Date.now()-40_000)-Date.parse(bundle.challenge.issuedAt);for(const f of ['issuedAt','expiresAt'])bundle.challenge[f]=shift(bundle.challenge[f],delta);
 const paths=[['observedAt'],['expiresAt'],['providerPolicyObservation','observedAt'],...['recoveryPointAt','sourceCutoffAt','restoreRequestedAt','verificationCompletedAt'].map(x=>['rpoRtoMeasurement',x]),...['startedAt','completedAt'].map(x=>['backupArtifact',x]),...['startedAt','completedAt'].map(x=>['restoreDrill',x]),...['windowStartedAt','windowCompletedAt'].map(x=>['productionNoMutation',x]),['cleanup','checkedAt'],['retention','retainedUntil']];for(const p of paths){let x=bundle.evidence;for(const k of p.slice(0,-1))x=x[k];x[p.at(-1)]=shift(x[p.at(-1)],delta);}
 bundle.challenge.providerPolicyDigest=g2Sha256(g2CanonicalJson(bundle.policy.providerPolicy));
 const challengeDigest=g2Sha256(g2CanonicalJson(bundle.challenge)),policyDigest=g2Sha256(g2CanonicalJson(bundle.policy));
 const envelopes=Object.fromEntries(G2_SEMANTIC_OPERATIONS.map(op=>[op,{schemaVersion:G2_ADAPTER_ENVELOPE_SCHEMA,semanticOperation:op,adapterVersion:'synthetic-local-adapter/1.0.0',challengeId:bundle.challenge.challengeId,runId:bundle.challenge.runId,nonce:bundle.challenge.nonce,collectorKeyId:bundle.challenge.collectorKeyId,challengeDigest,policyDigest,attestedAt:bundle.evidence.observedAt,payload:bundle.evidence[payloadField[op]]}]));
 const adapter=join(protectedDir,'synthetic-adapter.mjs');const adapterSource=`#!/usr/bin/node\nconst env=Object.keys(process.env).sort();if(JSON.stringify(env)!==JSON.stringify(['LANG','LC_ALL','PATH','TZ']))process.exit(91);const a=process.argv.slice(2),op=a[a.indexOf('--semantic-operation')+1],map=${JSON.stringify(envelopes)};if(a.length!==19||a[0]!=='collect'||a.at(-2)!=='--format'||a.at(-1)!=='json'||!map[op])process.exit(92);process.stdout.write(JSON.stringify(map[op]));\n`;await writeFile(adapter,adapterSource,{mode:0o500});await chmod(adapter,0o500);const digest=`sha256:${createHash('sha256').update(adapterSource).digest('hex')}`;
 const executable={path:adapter,realpath:adapter,sha256:digest,version:'synthetic-local-adapter/1.0.0',uid:process.getuid(),mode:0o500};const plan={schemaVersion:G2_OPERATION_PLAN_SCHEMA,challengeId:bundle.challenge.challengeId,runId:bundle.challenge.runId,nonce:bundle.challenge.nonce,keyId:bundle.challenge.collectorKeyId,challengeDigest,policyDigest,operations:G2_SEMANTIC_OPERATIONS.map(semanticOperation=>({semanticOperation,executable})),limits:{timeoutMs:3000,versionTimeoutMs:500,stdoutBytes:65536,stderrBytes:1024}};
 const keyring={schemaVersion:'wordle-provider-collector-keyring/v1',keys:[{keyId:bundle.challenge.collectorKeyId,publicKeyPem:publicKey.export({format:'pem',type:'spki'}).toString(),notBefore:new Date(Date.now()-3600_000).toISOString(),notAfter:new Date(Date.now()+3600_000).toISOString(),revokedAt:null}]};const values={challenge:bundle.challenge,policy:bundle.policy,'operation-plan':plan,keyring};const files={};for(const [name,value]of Object.entries(values)){files[name]=join(protectedDir,`${name}.json`);await writeFile(files[name],`${JSON.stringify(value)}\n`,{mode:0o600});await chmod(files[name],0o600);}files['signing-key']=join(protectedDir,'signing-key.pem');await writeFile(files['signing-key'],privateKey.export({format:'pem',type:'pkcs8'}),{mode:0o600});await chmod(files['signing-key'],0o600);
 const args=['--challenge',files.challenge,'--policy',files.policy,'--operation-plan',files['operation-plan'],'--signing-key',files['signing-key'],'--keyring',files.keyring,'--output-dir',output,'--collector-replay-dir',collectorReplay];return{root,protectedDir,output,collectorReplay,ahOutput,ahReplay,bundle,keyring,files,args,privateKey,publicKey,cleanup:()=>rm(root,{recursive:true,force:true})};
}
async function rewriteAdapter(s,replacement,limits={}){const plan=JSON.parse(await readFile(s.files['operation-plan'],'utf8')),path=plan.operations[0].executable.path;let source=await readFile(path,'utf8');source=source.replace('process.stdout.write(JSON.stringify(map[op]));',replacement);await chmod(path,0o700);await writeFile(path,source);await chmod(path,0o500);const digest=`sha256:${createHash('sha256').update(source).digest('hex')}`;for(const operation of plan.operations)operation.executable.sha256=digest;Object.assign(plan.limits,limits);await writeFile(s.files['operation-plan'],`${JSON.stringify(plan)}\n`,{mode:0o600});}
function ahArgs(s,response){const p=s.bundle.policy,f=response.files;return['--policy',s.files.policy,'--challenge',s.files.challenge,'--evidence',f.evidence,'--provider-receipt',f['provider-receipt'],'--keyring',s.files.keyring,'--expected-challenge-id',p.expectedChallengeId,'--expected-run-id',p.expectedRunId,'--expected-nonce',p.expectedNonce,'--expected-collector-key-id',p.expectedCollectorKeyId,'--expected-repository',p.repository,'--expected-source-git-sha',p.sourceGitSha,'--expected-source-artifact-digest',p.sourceArtifactDigest,'--expected-migration-digest',p.migrationDigest,'--expected-policy-digest',g2Sha256(g2CanonicalJson(p)),'--expected-provider-policy-digest',g2Sha256(g2CanonicalJson(p.providerPolicy)),'--expected-source-identity-digest',g2Sha256(g2CanonicalJson(p.identities.sourceProduction)),'--expected-restore-identity-digest',g2Sha256(g2CanonicalJson(p.identities.restoreDestination)),'--replay-dir',s.ahReplay,'--output-dir',s.ahOutput];}

test('real production collector executes synthetic adapter seven times then shipped Wave AH accepts its bundle',async()=>{const s=await fixture();try{const collected=await run(CLI,s.args);assert.equal(collected.code,0,collected.stderr);assert.equal(collected.stderr,'');const response=JSON.parse(collected.stdout);assert.equal(response.decision,'eligible_to_request_G2_approval');assert.equal((await readdir(s.collectorReplay)).length,1);assert.equal((await stat(response.commit)).mode&0o777,0o600);
 const evidence=JSON.parse(await readFile(response.files.evidence)),receipt=JSON.parse(await readFile(response.files['provider-receipt'])),inventory=JSON.parse(await readFile(response.files.inventory)),eligibility=JSON.parse(await readFile(response.files.eligibility));assert.deepEqual(inventory,deriveG2BackupRestoreInventory(evidence,s.bundle.challenge,s.bundle.policy));assert.equal(receipt.evidenceDigest,g2Sha256(g2CanonicalJson(evidence)));assert.equal(receipt.inventoryDigest,g2Sha256(g2CanonicalJson(inventory)));for(const field of ['hostedMutationAuthorized','g1Authorized','g2Authorized','backupExecutionAuthorized','restoreExecutionAuthorized','productionMutationAuthorized'])assert.equal(eligibility[field],false,field);for(const value of [evidence,receipt]){const unsigned={...value};delete unsigned.signature;assert.equal(verify(null,Buffer.from(g2CanonicalJson(unsigned)),s.publicKey,Buffer.from(value.signature.slice(8),'base64')),true);}
 const independently=evaluateG2BackupRestoreReadiness({challenge:s.bundle.challenge,evidence,providerReceipt:receipt,collectorPublicKey:s.publicKey,policy:s.bundle.policy,now:Date.now()});assert.equal(independently.decision,'eligible_to_request_G2_approval');const ah=await run(AH,ahArgs(s,response));assert.equal(ah.code,0,ah.stderr);assert.equal(JSON.parse(ah.stdout).decision,'eligible_to_request_G2_approval');assert.notEqual(s.collectorReplay,s.ahReplay);assert.equal((collected.stdout+collected.stderr+ah.stdout+ah.stderr).includes(CANARY),false);
 }finally{await s.cleanup();}});

test('closed CLI, output collision, collector replay and failures are stable and secret-free',async()=>{const s=await fixture();try{let r=await run(CLI,[...s.args,'--adapter-arg','evil']);assert.equal(r.code,2);assert.equal(r.stdout,'');assert.deepEqual(JSON.parse(r.stderr),{ok:false,code:'CLI_ARGUMENT_INVALID'});await writeFile(join(s.output,`${s.bundle.challenge.runId}.evidence.json`),'occupied\n',{mode:0o600});r=await run(CLI,s.args);assert.equal(r.code,4);assert.equal(JSON.parse(r.stderr).code,'OUTPUT_ALREADY_EXISTS');assert.deepEqual(await readdir(s.collectorReplay),[]);await rm(join(s.output,`${s.bundle.challenge.runId}.evidence.json`));r=await run(CLI,s.args);assert.equal(r.code,0,r.stderr);const other=join(s.root,'other');await mkdir(other,{mode:0o700});const args=[...s.args];args[args.indexOf('--output-dir')+1]=other;r=await run(CLI,args);assert.equal(r.code,3);assert.equal(r.stdout,'');assert.deepEqual(JSON.parse(r.stderr),{ok:false,code:'CHALLENGE_REPLAY'});assert.deepEqual(await readdir(other),[]);assert.equal(r.stderr.includes(CANARY),false);}finally{await s.cleanup();}});

test('strict protected collector inputs reject duplicate/trailing/depth and unsafe inode policy before subprocess or replay',async t=>{const cases=[
 ['duplicate',async s=>{const raw=await readFile(s.files.policy,'utf8');await writeFile(s.files.policy,raw.replace('{','{"repository":"duplicate/repo",'),{mode:0o600});},'DUPLICATE_JSON_KEY'],
 ['trailing',async s=>writeFile(s.files.challenge,`${await readFile(s.files.challenge,'utf8')}trailing`,{mode:0o600}),'JSON_SYNTAX'],
 ['depth',async s=>writeFile(s.files['operation-plan'],`${'['.repeat(33)}0${']'.repeat(33)}`,{mode:0o600}),'JSON_DEPTH'],
 ['permissive',async s=>chmod(s.files.keyring,0o640),'UNSAFE_INPUT_FILE'],
 ['hardlink',async s=>link(s.files.policy,`${s.files.policy}.hard`),'UNSAFE_INPUT_FILE'],
 ['symlink',async s=>{const real=`${s.files.challenge}.real`;await rename(s.files.challenge,real);await symlink(real,s.files.challenge);},'UNSAFE_INPUT_FILE'],
 ['alias',async s=>{s.args=[...s.args];s.args[s.args.indexOf('--signing-key')+1]=s.files.challenge;},'INPUT_FILE_ALIAS'],
 ];for(const [name,mutate,code]of cases)await t.test(name,async()=>{const s=await fixture();try{await mutate(s);const result=await run(CLI,s.args);assert.equal(result.code,2,result.stderr);assert.equal(result.stdout,'');assert.equal(JSON.parse(result.stderr).code,code);assert.deepEqual(await readdir(s.output),[]);assert.deepEqual(await readdir(s.collectorReplay),[]);assert.equal(result.stderr.includes(CANARY),false);}finally{await s.cleanup();}});});

test('concurrent collector nonce use has exactly one success and no partial loser bundle',async()=>{const s=await fixture();try{const other=join(s.root,'concurrent-output');await mkdir(other,{mode:0o700});const args=[...s.args];args[args.indexOf('--output-dir')+1]=other;const results=await Promise.all([run(CLI,s.args),run(CLI,args)]);assert.deepEqual(results.map(x=>x.code).sort((a,b)=>a-b),[0,3]);const loser=results.find(x=>x.code!==0);assert.equal(loser.stdout,'');assert.equal(JSON.parse(loser.stderr).code,'CHALLENGE_REPLAY');const published=(await readdir(s.output)).length+(await readdir(other)).length;assert.equal(published,5);assert.equal((results.map(x=>x.stdout+x.stderr).join('')).includes(CANARY),false);}finally{await s.cleanup();}});

test('adapter process failures have stable sanitized exits and never consume replay',async t=>{const cases=[
 ['nonzero','process.stderr.write(process.env.AI2_SECRET??"hidden");process.exit(17);',{},'OPERATION_FAILED'],
 ['timeout','await new Promise(r=>setTimeout(r,1000));',{timeoutMs:100},'PROCESS_TIMEOUT'],
 ['stdout-limit','process.stdout.write("x".repeat(300));',{stdoutBytes:256},'STDOUT_LIMIT'],
 ['stderr-limit','process.stderr.write((process.env.AI2_SECRET??"x").repeat(100));process.stdout.write(JSON.stringify(map[op]));',{stderrBytes:64},'STDERR_LIMIT'],
 ['malformed-secret','process.stdout.write((process.env.AI2_SECRET??"secret")+"{");',{},'ADAPTER_OUTPUT_JSON'],
 ['mixed-binding','const x=structuredClone(map[op]);x.challengeId="other-binding";process.stdout.write(JSON.stringify(x));',{},'ADAPTER_BINDING_MISMATCH'],
 ];for(const [name,source,limits,code]of cases)await t.test(name,async()=>{const s=await fixture();try{await rewriteAdapter(s,source,limits);const r=await run(CLI,s.args);assert.equal(r.code,2,r.stderr);assert.equal(r.stdout,'');assert.deepEqual(JSON.parse(r.stderr),{ok:false,code});assert.equal(r.stderr.includes(CANARY),false);assert.deepEqual(await readdir(s.output),[]);assert.deepEqual(await readdir(s.collectorReplay),[]);}finally{await s.cleanup();}});});

test('private/public mismatch is rejected before adapter execution or replay',async()=>{const s=await fixture();try{const {privateKey}=generateKeyPairSync('ed25519');await writeFile(s.files['signing-key'],privateKey.export({format:'pem',type:'pkcs8'}),{mode:0o600});const r=await run(CLI,s.args);assert.equal(r.code,2,r.stderr);assert.deepEqual(JSON.parse(r.stderr),{ok:false,code:'COLLECTOR_KEY_MISMATCH'});assert.deepEqual(await readdir(s.output),[]);assert.deepEqual(await readdir(s.collectorReplay),[]);}finally{await s.cleanup();}});

test('executable inode, mode, and hash drift is detected with the full dev/ino/mode/hash snapshot',async t=>{for(const [name,mutation]of [
 ['inode','await import("node:fs/promises").then(async f=>{const p='+JSON.stringify('PATH')+';});'],
 ['mode','await import("node:fs/promises").then(f=>f.chmod('+JSON.stringify('PATH')+',0o700));'],
 ['hash','await import("node:fs/promises").then(async f=>{await f.chmod('+JSON.stringify('PATH')+',0o700);await f.appendFile('+JSON.stringify('PATH')+',"\\n//drift");await f.chmod('+JSON.stringify('PATH')+',0o500);});'],
 ])await t.test(name,async()=>{const s=await fixture();try{const path=join(s.protectedDir,'synthetic-adapter.mjs');let action=mutation.replaceAll(JSON.stringify('PATH'),JSON.stringify(path));if(name==='inode')action=`await import("node:fs/promises").then(async f=>{await f.rename(${JSON.stringify(path)},${JSON.stringify(path+'.old')});await f.copyFile(${JSON.stringify(path+'.old')},${JSON.stringify(path)});await f.chmod(${JSON.stringify(path)},0o500);});`;await rewriteAdapter(s,`process.stdout.write(JSON.stringify(map[op]));if(op==='provider-policy-observation'){${action}}`);const r=await run(CLI,s.args);assert.equal(r.code,2,r.stderr);const expected=name==='mode'?'EXECUTABLE_POLICY_MISMATCH':'EXECUTABLE_CHANGED';assert.deepEqual(JSON.parse(r.stderr),{ok:false,code:expected});assert.deepEqual(await readdir(s.output),[]);assert.deepEqual(await readdir(s.collectorReplay),[]);}finally{await s.cleanup();}});const runner=await readFile(join(HERE,'g2-backup-restore-evidence-collector-runner.mjs'),'utf8');assert.match(runner,/\['dev','ino','uid','mode','nlink','sha256'\]/u);});

async function transactionFixture(){const root=await mkdtemp(join(tmpdir(),'g2-ai2-tx-')),output=join(root,'output'),replay=join(root,'replay');await mkdir(output,{mode:0o700});await mkdir(replay,{mode:0o700});const outputRoot=await openG2ProtectedDirectory(output),replayRoot=await openG2ProtectedDirectory(replay);return{root,output,replay,outputRoot,replayRoot,bundle:{challenge:{runId:`tx-${process.pid}-${Math.random().toString(16).slice(2)}`,nonce:`nonce-${process.pid}-${Math.random().toString(16).slice(2)}`},evidence:{x:1},providerReceipt:{x:2},inventory:{x:3},eligibility:{x:4}},async cleanup(){await outputRoot.handle.close();await replayRoot.handle.close();await rm(root,{recursive:true,force:true});}};}
test('commit-last transaction rejects deterministic inode races and rolls back every trusted final',async t=>{const cases=[
 ['late-output-collision','candidates-ready',async(s,c)=>writeFile(join(s.output,c.names.finals.evidence),'occupied',{mode:0o600})],
 ['candidate-hardlink','candidates-ready',async(s)=>{const name=(await readdir(s.output)).find(x=>x.endsWith('.candidate'));await link(join(s.output,name),join(s.root,'candidate-link'));}],
 ['candidate-removal','candidates-ready',async(s)=>{const name=(await readdir(s.output)).find(x=>x.endsWith('.candidate'));await rm(join(s.output,name));}],
 ['candidate-replacement','candidates-ready',async(s)=>{const name=(await readdir(s.output)).find(x=>x.endsWith('.candidate'));await rm(join(s.output,name));await writeFile(join(s.output,name),'replacement',{mode:0o600});}],
 ['marker-hardlink','replay-consumed',async(s,c)=>link(join(s.replay,c.markerName),join(s.root,'marker-link'))],
 ['marker-removal','replay-consumed',async(s,c)=>rm(join(s.replay,c.markerName))],
 ['marker-replacement','replay-consumed',async(s,c)=>{await rm(join(s.replay,c.markerName));await writeFile(join(s.replay,c.markerName),'replacement',{mode:0o600});}],
 ['final-hardlink','commit-published',async(s,c)=>link(join(s.output,c.names.finals.evidence),join(s.root,'final-link'))],
 ['final-removal','commit-published',async(s,c)=>rm(join(s.output,c.names.finals.evidence))],
 ['final-replacement','commit-published',async(s,c)=>{await rm(join(s.output,c.names.finals.evidence));await writeFile(join(s.output,c.names.finals.evidence),'replacement',{mode:0o600});}],
 ['commit-hardlink','commit-published',async(s,c)=>link(join(s.output,c.names.commit),join(s.root,'commit-link'))],
 ['commit-removal','commit-published',async(s,c)=>rm(join(s.output,c.names.commit))],
 ['commit-replacement','commit-published',async(s,c)=>{await rm(join(s.output,c.names.commit));await writeFile(join(s.output,c.names.commit),'replacement',{mode:0o600});}],
 ['output-root-replacement','candidates-ready',async s=>{await rename(s.output,`${s.output}.moved`);await mkdir(s.output,{mode:0o700});}],
 ['replay-root-replacement','candidates-ready',async s=>{await rename(s.replay,`${s.replay}.moved`);await mkdir(s.replay,{mode:0o700});}],
 ['late-commit-failure','commit-published',async()=>{throw Object.assign(new Error('late'),{code:'LATE_FAILURE'});}],
 ];for(const [name,stage,attack]of cases)await t.test(name,async()=>{const s=await transactionFixture();try{await assert.rejects(publishG2CollectorBundle({outputRoot:s.outputRoot,replayRoot:s.replayRoot,bundle:s.bundle,transactionHook:async(current,context)=>{if(current===stage)await attack(s,context);}}));const dirs=[s.output,`${s.output}.moved`];for(const dir of dirs){try{const files=await readdir(dir);assert.equal(files.some(x=>x.endsWith('.collector-commit.json')),false,files.join(','));assert.equal(files.some(x=>/\.(?:evidence|provider-receipt|inventory|eligibility)\.json$/u.test(x)),false,files.join(','));}catch{}}}finally{await s.cleanup();}});});

test('strace proves collector CLI plus exactly seven adapter execve calls and no socket/connect',async t=>{try{await stat('/usr/bin/strace');}catch{t.skip('strace unavailable');return;}const s=await fixture();const trace=join(s.root,'trace.log');try{const result=await new Promise((accept,reject)=>{const child=spawn('/usr/bin/strace',['-f','-e','trace=execve,connect,socket','-o',trace,process.execPath,CLI,...s.args],{stdio:['ignore','pipe','pipe'],env:{...process.env,AI2_SECRET:CANARY}}),out=[],err=[];child.stdout.on('data',x=>out.push(x));child.stderr.on('data',x=>err.push(x));child.on('error',reject);child.on('close',code=>accept({code,stdout:Buffer.concat(out).toString(),stderr:Buffer.concat(err).toString()}));});assert.equal(result.code,0,result.stderr);const traced=await readFile(trace,'utf8');assert.equal((traced.match(/execve\(/gu)??[]).length,8,traced);assert.equal(/socket\(|connect\(/u.test(traced),false,traced);}finally{await s.cleanup();}});

test('production import boundary has child_process only in runner and no transport/provider/database SDK imports',async()=>{for(const name of ['g2-backup-restore-evidence-collector.mjs','g2-backup-restore-evidence-collector-core.mjs','g2-backup-restore-evidence-collector-io.mjs','g2-backup-restore-evidence-collector-runner.mjs']){const source=await readFile(join(HERE,name),'utf8');assert.equal(source.includes('node:child_process'),name.endsWith('-runner.mjs'));assert.equal(/from ['"](?:node:)?(?:http2?|https|net|tls|dgram|dns)|from ['"](?:pg|postgres|vercel|railway|supabase)/u.test(source),false,name);}});
