import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { ROUTES, assertPublicPayloadSafe, runHostedSpeedSmoke, snapshotShape } from './hosted-speed-smoke-core.mjs';

const revision = 'git:deployed-revision';
const ids = Array.from({ length: 5 }, (_, i) => `00000000-0000-4000-8000-00000000000${i + 1}`);
const users = ['30000000-0000-4000-8000-000000000001', '30000000-0000-4000-8000-000000000002'];
const unrelatedUser = '30000000-0000-4000-8000-000000000003';
const tickets = ['40000000-0000-4000-8000-000000000001', '40000000-0000-4000-8000-000000000002'];
const match = '10000000-0000-4000-8000-000000000001';
const handles = ['ruby_one', 'ruby_two'];
const envelope = (value, status = 200) => ({ status, durationMs: 2, body: { data: value, error: null } });
const profile = (i, mode, after = false) => ({ userId: users[i], handle: handles[i], mode, rating: mode === 'speed_1v1' ? 1500 + (after ? (i ? -12 : 12) : 0) : 1600 + i, matchesPlayed: mode === 'speed_1v1' && after ? 1 : 0, unrated: !after, provisional: true, algorithm: mode === 'speed_1v1' ? 'speed_1v1_glicko_v1' : 'standard_1v1_glicko_v1', algorithmConfigVersion: mode === 'speed_1v1' ? 'speed_1v1_glicko_v1' : 'standard_1v1_glicko_v1' });
const board = (mode, after = false) => ({ mode, algorithm: mode === 'speed_1v1' ? 'speed_1v1_glicko_v1' : 'standard_1v1_glicko_v1', algorithmConfigVersion: mode === 'speed_1v1' ? 'speed_1v1_glicko_v1' : 'standard_1v1_glicko_v1', entries: mode === 'speed_1v1' && after ? users.map((userId, i) => ({ rank: i + 1, userId, handle: handles[i], rating: 1500 + (i ? -12 : 12), matchesPlayed: 1 })) : [] });
const emptyHistory = () => ({ items: [], pagination: { nextCursor: null } });
const history = (i) => ({ items: [{ matchId: match, mode: 'ranked', rankedMode: 'speed_1v1', rulesetVersion: 'speed_1v1_v1_75s', status: 'completed', ratingAlgorithm: 'speed_1v1_glicko_v1', ratingAlgorithmConfigVersion: 'speed_1v1_glicko_v1', startedAt: '2026-07-28T00:00:04.000Z', completedAt: '2026-07-28T00:00:05.000Z', viewer: { userId: users[i], placement: i + 1, outcome: i ? 'abandoned' : 'solved', finalScore: 0, ratingDelta: i ? -12 : 12 }, participants: users.map((userId, j) => ({ userId, handle: handles[j], displayName: handles[j], placement: j + 1, outcome: j ? 'abandoned' : 'solved', finalScore: 0, ratingDelta: j ? -12 : 12 })) }], pagination: { nextCursor: null } });
const result = () => ({ matchId: match, state: 'completed', rankedMode: 'speed_1v1', rulesetVersion: 'speed_1v1_v1_75s', ratingAlgorithm: 'speed_1v1_glicko_v1', ratingAlgorithmConfigVersion: 'speed_1v1_glicko_v1', completedAt: '2026-07-28T00:00:05.000Z', completionReason: 'all_players_terminal', ratingEvent: { eventId: '50000000-0000-4000-8000-000000000001', matchId: match, kind: 'ranked_match_completed', status: 'applied', algorithmVersion: 'speed_1v1_glicko_v1', participants: users.map((userId, i) => ({ userId, ratingBefore: 1500, ratingAfter: 1500 + (i ? -12 : 12), ratingDelta: i ? -12 : 12, placement: i + 1 })) }, finalStandings: users.map((userId, i) => ({ userId, placement: i + 1 })) });
function snap(actor, terminal = false, overrides = {}) { const i = actor === 'two' ? 1 : 0; return { matchId: match, roundId: '20000000-0000-4000-8000-000000000001', mode: 'speed_1v1', rulesetVersion: 'speed_1v1_v1_75s', readyLifecycleVersion: 'speed_ready_v2_first_ack_90s', state: terminal ? 'completed' : 'countdown', serverTime: '2026-07-28T00:00:01.250Z', invitationExpiresAt: '2026-07-28T00:01:30.000Z', readyWindowStartedAt: '2026-07-28T00:00:01.000Z', readyDeadlineAt: '2026-07-28T00:00:21.000Z', startsAt: '2026-07-28T00:00:04.000Z', deadlineAt: '2026-07-28T00:01:19.000Z', timeControl: { roundTimeMs: 75000, solveTimeBucketMs: 100, maxGuesses: 6 }, readiness: { phase: 'locked', viewerReady: true, readyCount: 2, viewerReadyAt: '2026-07-28T00:00:01.000Z', viewerReadyOperationId: ids[i + 2] }, myState: { acceptedGuesses: [], terminalReason: terminal ? 'solved' : null, guessesUsed: terminal ? 1 : null, solveElapsedMs: terminal ? 1_000 : null, result: terminal ? (i ? 'loss' : 'win') : null }, opponentProgress: { acceptedGuessCount: 0, terminal: false }, ...overrides }; }
function firstReady(actor, overrides = {}) { const i = actor === 'two' ? 1 : 0; return snap(actor, false, { state: 'waiting_opponent_ready', serverTime: '2026-07-28T00:00:01.100Z', startsAt: null, deadlineAt: null, readiness: { phase: 'opponent_ready', viewerReady: true, readyCount: 1, viewerReadyAt: '2026-07-28T00:00:01.000Z', viewerReadyOperationId: ids[i + 2] }, ...overrides }); }
function initial(overrides = {}) { return { ...snap('one'), state: 'waiting_invitation', serverTime: '2026-07-28T00:00:00.000Z', invitationExpiresAt: '2026-07-28T00:01:30.000Z', readyWindowStartedAt: null, readyDeadlineAt: null, startsAt: null, deadlineAt: null, readiness: { phase: 'invitation', viewerReady: false, readyCount: 0, viewerReadyOperationId: null }, ...overrides }; }
function mockTransport(options = {}) {
  const calls = []; let settled = false; let firstState = true; let readyPosts = 0;
  const matchedOpponent = (i) => options.missingMatchedOpponent ? null : { userId: options.duplicateMatchedOpponent ? users[0] : options.incorrectReciprocalOpponent ? unrelatedUser : users[1 - i], handle: handles[1 - i], displayName: handles[1 - i], ratingAtQueue: 1500, provisional: true };
  return { calls, async request({ actor, method, path, body }) {
    calls.push({ actor, method, path, body }); const i = actor === 'two' ? 1 : 0;
    if (path === ROUTES.health) return envelope({ status: 'ok' });
    if (path === ROUTES.ready) return envelope({ status: 'ok', revision, dependencies: { speedRuntime: { status: 'ok' }, speedLifecycleActivation: { status: 'ok' } } });
    if (path === ROUTES.catalog) return envelope({ modes: [{ id: 'speed_1v1', enabled: true, ...(options.speedQueueMissing ? {} : { queueEnabled: !options.speedQueueDisabled }), readyLifecycleVersion: 'speed_ready_v2_first_ack_90s', rulesetVersion: 'speed_1v1_v1_75s', ratingAlgorithmConfigVersion: 'speed_1v1_glicko_v1', timeControl: { roundTimeSeconds: options.catalogRoundMismatch ? 74 : 75, invitationWindowSeconds: 90, readyWindowSeconds: 20, readyWindowStartsOn: 'first_valid_ready_acknowledgement', countdownSeconds: options.catalogCountdownMismatch ? 4 : 3, maxGuesses: 6, solveTimeBucketMs: 100, tieBreaker: 'server_solve_time_bucket' } }, ...(options.standardMissing ? [] : [{ id: 'standard_1v1', enabled: !options.standardDisabled }])] });
    if (path === ROUTES.session) return { ...envelope({ mode: 'preview_demo_session', user: { id: (options.duplicateUser || options.duplicateActors) ? users[0] : users[i], email: null, profile: { handle: (options.duplicateHandle || options.duplicateActors) ? handles[0] : handles[i], displayName: handles[i] } }, session: { expiresAt: '2026-07-29T00:00:00.000Z', cookieName: 'wordle_session' } }), sessionIdentity: (options.duplicateCookie || options.duplicateActors) ? 'same-session' : `session-${i}` };
    if (path === ROUTES.history) return envelope(settled ? (options.nonConverged || options.historyNotConverged ? emptyHistory() : history(i)) : emptyHistory());
    if (path === ROUTES.profile(handles[i], 'speed_1v1')) return envelope(options.opaque && !settled ? { opaque: true } : profile(i, 'speed_1v1', settled && !options.nonConverged && !options.profileNotConverged));
    if (path === ROUTES.profile(handles[i], 'standard_1v1')) { const p = profile(i, 'standard_1v1'); if (settled && options.standardChanged) p.rating++; return envelope(p); }
    if (path === ROUTES.leaderboard('speed_1v1')) return envelope(board('speed_1v1', settled && !options.nonConverged && !options.leaderboardNotConverged));
    if (path === ROUTES.leaderboard('standard_1v1')) { const b = board('standard_1v1'); if (settled && options.standardChanged) b.entries.push({ rank: 1, userId: users[0], handle: handles[0], rating: 1, matchesPlayed: 1 }); return envelope(b); }
    if (path === ROUTES.queue) return envelope({ ticketId: options.duplicateTickets ? tickets[0] : tickets[i], mode: 'speed_1v1', rated: true, userId: users[i], state: i ? 'matched' : 'queued', matchedMatchId: i ? (options.splitMatch ? `${match}-other` : match) : null, matchedOpponent: i ? matchedOpponent(i) : null });
    if (path === ROUTES.currentSpeed) return envelope(settled ? (options.nonTerminalCleanup ? { ticketId: tickets[i], state: 'matched', matchedMatchId: match } : null) : { ticketId: options.duplicateTickets ? tickets[0] : tickets[i], mode: 'speed_1v1', rated: true, userId: users[i], state: 'matched', matchedMatchId: options.splitMatch && i ? `${match}-other` : match, matchedOpponent: matchedOpponent(i) });
    if (path === ROUTES.currentStandard) return envelope(null);
    if (path === ROUTES.state(match)) { if (firstState) { firstState = false; return envelope(initial(options.initial ?? {})); } return envelope(snap(actor, settled && !options.nonTerminalCleanup, options.missingTimes ? { readyWindowStartedAt: null } : options.deadlineMismatch ? { deadlineAt: '2026-07-28T00:01:18.000Z' } : options.immutableMismatch ? { readyDeadlineAt: '2026-07-28T00:00:22.000Z' } : options.readyWindowBudgetMismatch ? { readyDeadlineAt: '2026-07-28T00:00:22.000Z' } : options.startIdentityMismatch ? { startsAt: '2026-07-28T00:00:05.000Z', deadlineAt: '2026-07-28T00:01:20.000Z' } : options.countdownRemainingMismatch ? { serverTime: '2026-07-28T00:00:00.000Z' } : {})); }
    if (path === ROUTES.readyMatch(match)) { readyPosts++; const extra = options.missingTimes ? { readyWindowStartedAt: null } : options.deadlineMismatch ? { deadlineAt: '2026-07-28T00:01:18.000Z' } : (options.immutableMismatch && readyPosts === 2) ? { readyDeadlineAt: '2026-07-28T00:00:22.000Z' } : options.readyWindowBudgetMismatch ? { readyDeadlineAt: '2026-07-28T00:00:22.000Z' } : options.countdownRemainingMismatch ? { serverTime: '2026-07-28T00:00:00.000Z' } : {}; const response = envelope(readyPosts === 1 ? firstReady(actor, extra) : snap(actor, false, extra), 201); if (options.timeoutSecond && readyPosts === 2) { const error = new Error('timed out after commit'); error.code = 'TIMEOUT'; error.durationMs = 35000; throw error; } return response; }
    if (path === ROUTES.forfeit(match)) { settled = true; return envelope({ matchId: match, state: 'completed' }, 201); }
    if (path === ROUTES.result(match)) { const r = result(); if (options.spoiler) r.answerWordHash = 'bad'; if (options.nonConverged) r.ratingEvent.status = 'pending'; return envelope(r); }
    return envelope({ opaque: true });
  } };
}
async function run(options = {}) { const transport = mockTransport(options); let tick = 0; const evidence = await runHostedSpeedSmoke({ transport, expectedRevision: revision, operationIds: ids, monotonicNow: () => ++tick / 10, sleep: async () => {} }); return { evidence, calls: transport.calls }; }
const expectFail = async (options, code) => { const { evidence } = await run(options); assert.equal(evidence.result, 'FAIL', JSON.stringify(evidence)); assert.match(evidence.failureCode, code instanceof RegExp ? code : new RegExp(`^${code}`)); };

describe('truthful hosted Speed smoke core (local deterministic only)', () => {
  it('accepts nullable guessesUsed in a realistic preterminal snapshot', () => { assert.equal(snapshotShape(snap('one'), match).myState.guessesUsed, null); });
  it('rejects guessesUsed zero rather than treating it as preterminal progress', () => { const invalid = snap('one'); invalid.myState.guessesUsed = 0; assert.throws(() => snapshotShape(invalid, match), /state_payload_invalid/); });
  it('passes a realistic lifecycle whose public snapshots omit participants', async () => { const fixture = initial(); assert.equal(Object.hasOwn(fixture, 'participants'), false); const { evidence, calls } = await run(); assert.equal(evidence.result, 'PASS', JSON.stringify(evidence)); assert.equal(evidence.lifecycleCount, 1); assert.equal(evidence.checks.cleanup, true); assert.equal(evidence.checks.distinctActors, true); assert.equal(calls.filter((c) => c.path === ROUTES.readyMatch(match)).length, 2); assert.equal(calls.filter((c) => c.path === ROUTES.forfeit(match)).length, 1); });
  it('fails opaque 2xx payloads', async () => expectFail({ opaque: true }, 'profile_payload_invalid'));
  it('fails missing immutable identity timestamps', async () => expectFail({ missingTimes: true }, 'immutable_readyWindowStartedAt_missing'));
  it('fails deadline budget mismatch before ready mutation', async () => { const { evidence, calls } = await run({ initial: { invitationExpiresAt: '2026-07-28T00:00:39.999Z' } }); assert.equal(evidence.failureCode, 'invitation_deadline_budget_insufficient'); assert.equal(calls.some((c) => c.path === ROUTES.readyMatch(match)), false); });
  it('fails exact round deadline duration mismatch', async () => expectFail({ deadlineMismatch: true }, 'round_deadline_budget_mismatch'));
  it('fails a duplicate cookie independently', async () => expectFail({ duplicateCookie: true }, 'duplicate_session_cookie'));
  it('fails a duplicate handle independently', async () => expectFail({ duplicateHandle: true }, 'duplicate_actor_handle'));
  it('fails a duplicate user independently', async () => expectFail({ duplicateUser: true }, 'duplicate_actor_user'));
  it('fails duplicate tickets', async () => expectFail({ duplicateTickets: true }, 'distinct_ticket_identity_required'));
  for (const [name, options] of [
    ['duplicate', { duplicateMatchedOpponent: true }],
    ['missing', { missingMatchedOpponent: true }],
    ['incorrect reciprocal', { incorrectReciprocalOpponent: true }],
  ]) it(`fails ${name} matchedOpponent identities before ready`, async () => { const { evidence, calls } = await run(options); assert.equal(evidence.failureCode, 'distinct_match_participants_required'); assert.equal(calls.some((c) => c.path === ROUTES.readyMatch(match)), false); });
  it('fails split match identity', async () => expectFail({ splitMatch: true }, 'exactly_one_fresh_match_required'));
  it('fails configured ready-window duration mismatch', async () => expectFail({ readyWindowBudgetMismatch: true }, 'ready_deadline_budget_mismatch'));
  it('fails ready-window immutable identity mismatch', async () => expectFail({ immutableMismatch: true }, 'immutable_readyDeadlineAt_mismatch'));
  it('fails start/deadline immutable identity mismatch', async () => expectFail({ startIdentityMismatch: true }, 'immutable_startsAt_mismatch'));
  it('fails countdown remaining-time over configured duration', async () => expectFail({ countdownRemainingMismatch: true }, 'countdown_identity_budget_mismatch'));
  it('fails catalog countdown/round identity mismatch', async () => { await expectFail({ catalogCountdownMismatch: true }, 'speed_catalog_mismatch'); await expectFail({ catalogRoundMismatch: true }, 'speed_catalog_mismatch'); });
  it('accepts a healthy Standard catalog mode without Speed-only queueEnabled', async () => { const { evidence } = await run(); assert.equal(evidence.result, 'PASS', JSON.stringify(evidence)); });
  it('fails pre-statefully when Standard is disabled or missing', async () => { for (const options of [{ standardDisabled: true }, { standardMissing: true }]) { const { evidence, calls } = await run(options); assert.equal(evidence.failureCode, 'standard_catalog_unavailable'); assert.equal(evidence.sessionsCreated, 0); assert.equal(calls.some((call) => call.path === ROUTES.session), false); } });
  it('keeps Speed queueEnabled strict', async () => { for (const options of [{ speedQueueDisabled: true }, { speedQueueMissing: true }]) { const { evidence, calls } = await run(options); assert.equal(evidence.result, 'FAIL', JSON.stringify(evidence)); assert.match(evidence.failureCode, /^speed_catalog_mismatch/); assert.equal(evidence.sessionsCreated, 0); assert.equal(calls.some((call) => call.path === ROUTES.session), false); } });
  it('allows mandatory guess-shaped public progress but rejects answer authority', () => { assert.equal(assertPublicPayloadSafe({ timeControl: { maxGuesses: 6 }, myState: { acceptedGuesses: [{ guess: 'crane', guessNumber: 1 }], guessesUsed: 1 }, opponentProgress: { acceptedGuessCount: 1 } }), true); assert.throws(() => assertPublicPayloadSafe({ nested: { answerWordHash: 'bad' } }), /public_payload_forbidden_authority/); });
  it('fails forbidden answer authority recursively in accepted public payloads', async () => expectFail({ spoiler: true }, 'public_payload_forbidden_authority'));
  it('fails non-converged result/history/profile/leaderboard', async () => expectFail({ nonConverged: true }, 'result_payload_invalid'));
  it('fails a completed result absent from either history', async () => expectFail({ historyNotConverged: true }, 'history_not_converged'));
  it('fails Speed profile rating/match-count non-convergence', async () => expectFail({ profileNotConverged: true }, 'profile_not_converged'));
  it('fails Speed leaderboard non-convergence', async () => expectFail({ leaderboardNotConverged: true }, 'leaderboard_not_converged'));
  it('fails changed Standard baselines', async () => expectFail({ standardChanged: true }, 'standard_not_isolated'));
  it('fails non-terminal ticket/match cleanup', async () => expectFail({ nonTerminalCleanup: true }, 'terminal_cleanup_not_verified'));
  it('keeps no blind mutation retry and unique confirmation IDs', async () => { const { evidence, calls } = await run(); assert.equal(evidence.ready.blindRetries, 0); const writes = calls.filter((c) => c.body?.clientRequestId); assert.equal(writes.length, 5); assert.equal(new Set(writes.map((c) => c.body.clientRequestId)).size, 5); });
  it('merges a timed-out concurrent result with exactly one bounded GET recovery and never retries ready', async () => { const { evidence, calls } = await run({ timeoutSecond: true }); assert.equal(evidence.result, 'PASS', JSON.stringify(evidence)); assert.deepEqual(evidence.ready.statuses, [201, 'timeout']); assert.equal(evidence.ready.recoveredByCurrentState, 1); assert.equal(calls.filter((c) => c.path === ROUTES.readyMatch(match)).length, 2); assert.equal(calls.filter((c) => c.path === ROUTES.state(match)).length, 4); });
});
