export const SPEED_RECONCILER_RUNTIME_IDENTITY = 'speed_reconciler_runtime_v2_dependency_minimal_10s' as const;
export const SPEED_RECONCILER_INTERVAL_MS = 1_000 as const;
export const SPEED_RECONCILER_BATCH_SIZE = 10 as const;
export const SPEED_RECONCILER_SELECTION_LIMIT = 11 as const;
export const SPEED_RECONCILER_MAX_WAIT_MS = 1_000 as const;
export const SPEED_RECONCILER_LOCK_TIMEOUT_MS = 1_000 as const;
export const SPEED_RECONCILER_STATEMENT_TIMEOUT_MS = 7_000 as const;
export const SPEED_RECONCILER_TRANSACTION_TIMEOUT_MS = 8_000 as const;
export const SPEED_RECONCILER_MAX_PASS_MS = 10_000 as const;
export const SPEED_RECONCILER_SUCCESS_FRESHNESS_MS = 12_000 as const;
export const SPEED_RECONCILER_PASS_RESERVE_MS = 1_000 as const;

if (SPEED_RECONCILER_SELECTION_LIMIT !== SPEED_RECONCILER_BATCH_SIZE + 1
  || SPEED_RECONCILER_MAX_WAIT_MS + SPEED_RECONCILER_TRANSACTION_TIMEOUT_MS + SPEED_RECONCILER_PASS_RESERVE_MS > SPEED_RECONCILER_MAX_PASS_MS
  || SPEED_RECONCILER_LOCK_TIMEOUT_MS > SPEED_RECONCILER_STATEMENT_TIMEOUT_MS
  || SPEED_RECONCILER_STATEMENT_TIMEOUT_MS >= SPEED_RECONCILER_TRANSACTION_TIMEOUT_MS
  || SPEED_RECONCILER_INTERVAL_MS <= 0
  || SPEED_RECONCILER_BATCH_SIZE <= 0
  || SPEED_RECONCILER_SUCCESS_FRESHNESS_MS < SPEED_RECONCILER_MAX_PASS_MS + SPEED_RECONCILER_INTERVAL_MS) {
  throw new Error('invalid_speed_reconciler_budget');
}

export const SPEED_RECONCILER_BUDGET = Object.freeze({
  runtimeIdentity: SPEED_RECONCILER_RUNTIME_IDENTITY,
  intervalMs: SPEED_RECONCILER_INTERVAL_MS,
  batchSize: SPEED_RECONCILER_BATCH_SIZE,
  selectionLimit: SPEED_RECONCILER_SELECTION_LIMIT,
  maxWaitMs: SPEED_RECONCILER_MAX_WAIT_MS,
  lockTimeoutMs: SPEED_RECONCILER_LOCK_TIMEOUT_MS,
  statementTimeoutMs: SPEED_RECONCILER_STATEMENT_TIMEOUT_MS,
  transactionTimeoutMs: SPEED_RECONCILER_TRANSACTION_TIMEOUT_MS,
  maxPassMs: SPEED_RECONCILER_MAX_PASS_MS,
  successFreshnessMs: SPEED_RECONCILER_SUCCESS_FRESHNESS_MS,
  passReserveMs: SPEED_RECONCILER_PASS_RESERVE_MS,
});
