export const clientEventNames = {
  lobbySubscribe: 'lobby.subscribe',
  lobbySetReady: 'lobby.set_ready',
  lobbyUpdateSettings: 'lobby.update_settings',
  lobbyStartMatch: 'lobby.start_match',
  lobbyLeave: 'lobby.leave',
  matchmakingSubscribe: 'matchmaking.subscribe',
  matchSubscribe: 'match.subscribe',
  guessSubmit: 'guess.submit',
  sessionResync: 'session.resync',
} as const;

export const serverEventNames = {
  connectionReady: 'connection.ready',
  connectionStateChanged: 'connection.state_changed',
  lobbySnapshot: 'lobby.snapshot',
  lobbyMemberJoined: 'lobby.member_joined',
  lobbyMemberLeft: 'lobby.member_left',
  lobbyMemberReadyChanged: 'lobby.member_ready_changed',
  lobbyReadyReset: 'lobby.ready_reset',
  lobbySettingsUpdated: 'lobby.settings_updated',
  lobbyMatchStarting: 'lobby.match_starting',
  lobbyStartFailed: 'lobby.start_failed',
  matchmakingStatus: 'matchmaking.status',
  matchmakingMatched: 'matchmaking.matched',
  matchmakingDuplicateQueue: 'matchmaking.duplicate_queue',
  matchmakingTimeout: 'matchmaking.timeout',
  matchSnapshot: 'match.snapshot',
  matchStarted: 'match.started',
  roundCountdownStarted: 'round.countdown_started',
  roundStarted: 'round.started',
  guessAccepted: 'guess.accepted',
  guessRejected: 'guess.rejected',
  roundPlayerProgress: 'round.player_progress',
  roundPlayerSolved: 'round.player_solved',
  roundFinalizing: 'round.finalizing',
  roundEnded: 'round.ended',
  matchRoundIntermission: 'match.round_intermission',
  matchFinalizing: 'match.finalizing',
  matchCompleted: 'match.completed',
  matchVoided: 'match.voided',
  sessionResyncResult: 'session.resync_result',
  error: 'error',
} as const;
